AnimationTree simplification and expansion
godotengine/godot-docs pull request #10072
Opened 2024-10-11 16:14 UTC by saabdo42

Simplified AnimationTree language, added documentation for Advance Expression, made images webp and colorblind friendly with more descriptive names.

2024-10-11 17:08 UTC, fire commented
Is there a good way to preview doc changes?

2024-10-11 19:00 UTC, fire commented
Not familiar with spinx errors.

```
Warning, treated as error:
/home/runner/work/godot-docs/godot-docs/tutorials/animation/animation_tree.rst:19:Title underline too short.

AnimationTree and AnimationPlayer
-------------------------
make: *** [Makefile:37: dummy] Error 2
```

2024-10-12 02:33 UTC, saabdo42 commented
Ok just fixed that error

2024-10-12 14:43 UTC, saabdo42 commented
I'm not sure how to assign issues to pull requests, but this fixes #9699 and #7753

2024-10-12 17:11 UTC, fire commented
Add
Add this to your first post.
```
Fixes: https://github.com/godotengine/godot-docs/issues/9699
Fixes: https://github.com/godotengine/godot-docs/issues/7753
``

2024-10-29 00:36 UTC, skyace65 commented
This PR needs to be rebased.

2024-10-29 02:45 UTC, saabdo42 commented
What does that mean? (sorry lol)

2024-10-31 18:39 UTC, fire commented
Let me know if you have any questions after reading this. https://docs.godotengine.org/en/stable/contributing/workflow/pr_workflow.html

2025-03-19 23:47 UTC, saabdo42 commented
Any update on this?

2025-03-26 16:32 UTC, skyace65 commented
Still need to review this, apologies for the long wait

2025-03-28 20:48 UTC, skyace65 requested changes
Finally got around to looking at this

2025-03-28 20:48 UTC, skyace65 commented on tutorials/animation/img/animtree1.png
So this file, as well as any others. The were just converted and renamed to webp's should be put back in. We don't want to have all webp's just for the sake of having webp's. Doing this just makes the page update take up more space than it needs too.

2025-03-28 20:48 UTC, skyace65 commented on tutorials/animation/animation_tree.rst
> +<<<<<<< HEAD
something wasn't done properly here during a rebase

2025-03-28 20:48 UTC, skyace65 commented on tutorials/animation/animation_tree.rst
> +>>>>>>> db6fde45d (AnimationTree documentation overhaul)
Smae thing here

2025-03-28 20:48 UTC, skyace65 commented on tutorials/animation/animation_tree.rst
> +.. image:: img/animtree_blendspace1d.webp
There's existing sections about blendspace 1D and 2D earlier in the page, not sure what happened here, or if something wasn't removed that was supposed to be.

2025-03-31 18:10 UTC, saabdo42 commented on tutorials/animation/img/animtree1.png
Doesn't the guidelines for writing documentation say the image format should be webp? [https://docs.godotengine.org/en/stable/contributing/documentation/docs_image_guidelines.html#format-conversion](https://docs.godotengine.org/en/stable/contributing/documentation/docs_image_guidelines.html#format-conversion)

2025-04-01 23:21 UTC, skyace65 commented on tutorials/animation/img/animtree1.png
Yes, and for any new image, or updated image it should be a webp. This is an image that's not being changed at all, we don't do conversions for the sake of conversions.

2025-04-09 03:05 UTC, saabdo42 commented on tutorials/animation/img/animtree1.png
Ok, i just changed the imgs that weren't edited back to pngs, but kept their new names, also i left the edited imgs as webps

2025-04-12 14:42 UTC, skyace65 approved these changes

2025-06-08 17:54 UTC, merged

2025-06-08 17:54 UTC, skyace65 commented
Merging this as is due to the lack of a response from the animation team.

@saabdo42 Thanks! Apologies on how long this took, congrats on your first merged PR!