Update "Size and anchors" to reflext Godot 4.3 terminology
godotengine/godot-docs pull request #10216
Opened 2024-11-05 21:53 UTC by mikael-ros

It included terms like "margin" which seem to have been replaced by "Anchor Offsets".

I also replaced the relevant screenshots, but chose not to delete the old ones as I didn't want to accidentally break another article.

This is my second ever contribution to any open source project, so please do have patience with me if I got something wrong. I'll try my best to fix it.

2024-11-05 23:12 UTC, tetrapod00 requested changes
Thank you for contributing by updating this page! There are some changes that need to be made, though:
- You'll need to update the images to preserve their original meaning, and change the format to WebP.
- There are also a few style changes to make.

The content looks fine, as it's mostly unchanged other than the 3.x->4.x terminology changes.

2024-11-05 23:16 UTC, tetrapod00 commented
I believe this might close https://github.com/godotengine/godot-docs/issues/9950.

2024-11-05 23:22 UTC, mikael-ros commented
Thank you for the thorough and respectful comments and suggestions. I will go through them tomorrow when I have time. 

I don't know why I didn't realize that the images were baked in collages whilst editing, a bit of a oversight. I'll take and edit new screenshots tomorrow as well :)

2024-11-05 23:35 UTC, tetrapod00 commented
> I'll take and edit new screenshots tomorrow as well

If you are also taking new screenshots of the control examples, please use ``fffb44`` yellow for the text and lines instead of red, since it's better for colorblindness. See [here](https://docs.godotengine.org/en/stable/contributing/documentation/docs_image_guidelines.html#outlines-arrows-and-text).

2024-11-05 23:40 UTC, mikael-ros commented
Alright, will do. Thank you for the tip! :)

2024-11-06 13:21 UTC, AThousandShips commented on tutorials/ui/size_and_anchors.rst
> +There are several ways to attain this, but for now, let's just imagine
```suggestion
There are several ways to achieve this, but for now, let's just imagine
```
Or keep as it was

2024-11-07 00:39 UTC, tetrapod00 commented
When I reviewed, I didn't notice this is a duplicate of https://github.com/godotengine/godot-docs/pull/10005 and https://github.com/godotengine/godot-docs/pull/8855. 

This PR makes the most minimal changes, only swapping terminiology and updating the screenshots.
https://github.com/godotengine/godot-docs/pull/10005 is a larger rewrite of the page. It is not yet reviewed at all.
https://github.com/godotengine/godot-docs/pull/8855 is also a larger rewrite, which builds off *another* PR https://github.com/godotengine/godot-docs/pull/7106. It has one review, but not from a maintainer or frequent contributor.

I would tentatively suggest bringing this PR to a mergable state, which would make this page at not obiously incorrect. Then we can consider salvaging some of the other two PRs to rewrite the page more completely.

2024-11-07 20:36 UTC, mikael-ros commented on tutorials/ui/size_and_anchors.rst
> +ratios, resolutions and user scaling. Whilst some configurations may be more
I'll try to clean it up, thank you for the suggestion. I'll commit the correction for now

2024-11-07 20:38 UTC, mikael-ros commented on tutorials/ui/size_and_anchors.rst
>  adjust from 0 (top of parent) to 1.0 (bottom of parent) with 0.5 being
Alright, I wasn't aware reStructuredText supported the backtick syntax (never used reStructuredText before). Will consider.

2024-11-07 21:32 UTC, mikael-ros commented
Should hopefully be up to spec now. Let me know if there's anything else I need to do.

2024-11-07 21:36 UTC, mikael-ros commented
I also removed the old images now. I did a search with Visual Studio Code, and it scored no hits on any of the files removed.

2024-11-07 21:42 UTC, mikael-ros commented
Hopefully addressed the wordy paragraph I introduced in the original pull request now, too.

2024-11-07 21:46 UTC, tetrapod00 commented on tutorials/ui/img/offset.webp
The yellow text isn't really readable in these. How did the backgrounds end up so light? 

If you take screenshots with the default control theme on a default editor background, yellow text is perfectly readable:
![Godot_v4 3-stable_mono_win64_ePzcc2aQHg](https://github.com/user-attachments/assets/ce6b222c-b67c-4a46-bf40-e261d90aba24)

I would suggest either:
- Take the screenshots again, using default editor settings (you might have changed some settings?)
- Use a dark color like black for the lines and text, and keep the current light color background

2024-11-07 21:52 UTC, tetrapod00 commented on tutorials/ui/img/offset.webp
Oh, my bad, the light background color is how GitHub previews transparent images, but I'm not sure if a transparent background is quite right, either.

2024-11-07 21:54 UTC, mikael-ros commented on tutorials/ui/img/offset.webp
A transparent image is more flexible, in my own opinion. The originals were transparent too, but I'm not sure whats preferable

2024-11-07 22:06 UTC, tetrapod00 commented on tutorials/ui/img/offset.webp
A transparent image is better in the abstract but doesn't work in this particular case, where we need images that look nice on a default light background (but also look okay on the automatic dark modes that most browsers support now).

The quickest fix would be to replace the transparent background with the default editor background of `4d4d4d`. In krita you can do that by adding a new layer behind all the existing stuff and use either the fill tool or a rectangle to fill the background.

I'd recommend doing that, since this page is likely to get more improvements after this PR and there is no guarantee that these images will remain used. No need to do too much work polishing them.

2024-11-07 22:56 UTC, mikael-ros commented on tutorials/ui/img/offset.webp
That's understandable. The usual way I'd go about these things when doing web development is making sure theres always a middle ground color behind any image to act as a fallback, but I understand if that is not possible with the tooling used for this documentation.

I will fix this tomorrow :)

2024-11-07 23:07 UTC, tetrapod00 commented on tutorials/ui/img/offset.webp
I think we probably *can* add such a background, but it's not currently done because there's not a huge need for it. 90% of images in the docs are screenshots.

2024-11-08 13:38 UTC, mikael-ros commented on tutorials/ui/img/offset.webp
Understandable. I will fix the screenshots for now - will see if I commit a seperate PR at some other point to provide greater support for transparent images :o

2024-11-08 13:43 UTC, mikael-ros commented
I have now replaced the transparent images with ones including a backdrop of ``4d4d4d``. as suggested by @tetrapod00.

2024-11-08 19:22 UTC, tetrapod00 approved these changes
Looks good to me, thanks for making all the changes! This will be reviewed by at least one other reviewer, then it should be good to merge.

Note that at some point you should squash all the commits, [as described here](https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html#the-interactive-rebase). We prefer one commit per PR (though it's less strict in the docs repo). You can either do so now, or after all reviews are done.

For other reviewers: as noted in https://github.com/godotengine/godot-docs/pull/10216#issuecomment-2461087672 (and the older PRs linked), this page still needs a larger rewrite at some point. This PR makes the page factually correct, but the page is still not really the right tutorial for using anchors and offsets *in Godot 4*. At some point I'll try to salvage the other two older PRs into a full rewrite.

2024-11-08 19:43 UTC, mikael-ros commented
Thank you :) The larger rewrite does sound like a good idea.

I'll look into squashing in a bit. I usually don't squash since I prefer the granularity, but I definetely understand why you'd want a cleaner commit history in such a large project.

2024-11-08 21:49 UTC, mikael-ros commented
I'm not sure if this ended up being correct... 

It says *"``x`` authored and Mikael committed"*, is that the intended outcome?

I put ``fixup`` on every line I wanted to squash, as the docs recommended. It seems that the page is correct by the latest commit.

Sorry for my naivety. Whilst I am studying computer science, they haven't been very rigorous with git past the very basics and cherrypicked examples - so I am very much out of my depth here. I have a backup of my repo in case I need to redo this.

2024-11-08 22:13 UTC, tetrapod00 commented
Your commit 50e8733ed662593e655e74c5ba5a5c5ac7500306 looks correctly squashed, but now you also have the unrelated changes that have been merged in `master` since you first made this PR. I'm not sure how to untangle that 😅 

Usually to rebase you can do this (see [here](https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html#updating-your-branch))
```
git pull --rebase upstream master
```
then 
```
git push --force origin your-branch-name
```
But in this case I'm not sure if more needs to be done. Maybe you can interactive rebase again?

2024-11-08 22:29 UTC, mikael-ros commented
I think it might be correct now. It turned out that my ``upstream`` wasn't properly set earlier. Now it was vastly simpler. It should be correct now :sweat_smile:

2024-11-08 23:01 UTC, Calinou approved these changes
Thanks! Congratulations for your first merged pull request :tada:

2024-11-08 23:08 UTC, merged

2024-11-09 01:28 UTC, mikael-ros commented
Thank you :)

2024-11-30 06:31 UTC, mhilbrunner commented
Cherrypicked to 4.3 in https://github.com/godotengine/godot-docs/pull/10346.