Add info about layer mask exporting to physics_introduction.rst
godotengine/godot-docs pull request #10242
Opened 2024-11-10 16:31 UTC by notPelf

The docs page for raycasting provides a link to the physics introduction page for how to set a collision mask on a raycast created in code. The physics introduction page does not mention export annotations for exporting a collision mask. This pull request adds a brief bit about exporting layer masks, and links to the export annotation docs page.

2024-11-10 16:55 UTC, tetrapod00 requested changes
Good idea but needs so the cross-reference link works

2024-11-10 22:24 UTC, tetrapod00 commented on tutorials/physics/physics_introduction.rst
> +    # @export_flags_2d_physics var layers_2d_physics
```suggestion
    @export_flags_2d_physics var layers_2d_physics
```
Sorry, I missed that the example was commented out before. Besides that LGTM

2024-11-11 02:24 UTC, tetrapod00 approved these changes

2024-11-17 10:21 UTC, mhilbrunner approved these changes

2024-11-17 10:22 UTC, merged

2024-11-17 10:23 UTC, mhilbrunner commented
Thanks, merged! For future PRs, please note changes should go against the `master` branch by default unless they only apply to a specific old version. We'll handle cherrypicking the change to old versions.