POT Generator: Document `TRANSLATORS:` and `NO_TRANSLATE` comments
godotengine/godot-docs pull request #10342
Opened 2024-11-29 15:21 UTC by dalexeev

* See https://github.com/godotengine/godot/pull/98099.

2024-11-29 20:13 UTC, skyace65 requested changes

2024-11-29 20:13 UTC, skyace65 commented on tutorials/i18n/localization_using_gettext.rst
> +See :ref:`below <doc_localization_using_gettext_gdscript>` how to add comments for translators
```suggestion
See :ref:`below <doc_localization_using_gettext_gdscript>` for how to add comments for translators
```

2024-11-29 22:47 UTC, skyace65 approved these changes

2024-11-30 00:54 UTC, mhilbrunner approved these changes

2024-11-30 00:54 UTC, merged

2024-11-30 00:54 UTC, mhilbrunner commented
Thanks!