Update 04.creating_the_enemy.rst
godotengine/godot-docs pull request #10455
Opened 2024-12-31 10:12 UTC by iv0rye

Added a short explanation of the QueueFree() function.

2024-12-31 12:50 UTC, AThousandShips requested changes

2024-12-31 12:50 UTC, AThousandShips commented on getting_started/first_2d_game/04.creating_the_enemy.rst
> +``QueueFree()`` is a function that essentially 'frees', or deletes, the node at the end of the frame.
```suggestion
``queue_free()`` is a function that essentially 'frees', or deletes, the node at the end of the frame.
```
Should use the `GDScript` naming as for other methods

2024-12-31 19:36 UTC, tetrapod00 approved these changes
It's true and it describes what the code just added actually does.

I tend to err on the side of including small changes to the Getting Started tutorials.

2025-01-21 02:48 UTC, skyace65 approved these changes

2025-01-21 02:48 UTC, merged

2025-01-21 02:48 UTC, skyace65 commented
Thanks! And congrats on your first merged PR!