Update exporting_for_web.rst
godotengine/godot-docs pull request #2510
Opened 2019-06-06 16:30 UTC by BaseCrusher

Added a description of how to use external files in HTML export as well as a simple example of how to do this. Lines 165 - 182
I'm sure the language can be improved. But my English isn't good enough to do so. :(

2020-09-09 11:58 UTC, BaseCrusher commented
Will this get merged?

2020-09-09 12:04 UTC, Calinou requested changes
PS: Please make your fork repository public so we can make proper suggestions as supported by GitHub :slightly_smiling_face:

2020-09-09 12:04 UTC, Calinou commented on getting_started/workflow/export/exporting_for_web.rst
> +Use the deafult HTML page `/misc/dist/html/full-size.html <https://github.com/godotengine/godot/blob/master/misc/dist/html/full-size.html>`__. as a refrence
"deafult" -> "default"

2020-09-09 12:04 UTC, Calinou commented on getting_started/workflow/export/exporting_for_web.rst
> +and replace the lines 250 - 255.
"250 - 255" -> "250 to 255 with:"

2020-09-11 15:52 UTC, BaseCrusher commented
> PS: Please make your fork repository public so we can make proper suggestions as supported by GitHub 🙂

Sadly, it seems that I've deleted the forked repo. I could fork it again and create a new pull request or we stay on this one. I don't know which of this two optiones would be better for you.

2020-09-11 17:15 UTC, Calinou commented
@BaseCrusher Feel free to fork it again and create a new pull request.

2020-09-15 08:00 UTC, BaseCrusher commented
@Calinou I've created a new pull request.
https://github.com/godotengine/godot-docs/pull/4015

2020-09-17 19:25 UTC, NathanLovato commented
Closing as there's a new PR for this

2020-09-17 19:25 UTC, closed without merging