Clarify root node type in your first game
godotengine/godot-docs pull request #3570
Opened 2020-05-20 20:46 UTC by skyace65

Clarifies that the root node of the main scene in your first game is a Node node. This was the best way I could explain it without going in detail about what a Node node is, I'm open to suggestions if anyone thinks they can improve this. closes #3452 (the rest of that issue was fixed in another PR)

2020-05-20 21:19 UTC, cbscribe requested changes
Is this really a problem? I've been through this tutorial extensively with a large number of students of varying ages and this one has never made the list of pain points. "Node" is highlighted and linked.

That said, if folks think it's necessary, I've made some recommendations for wording changes.

2020-05-20 21:19 UTC, cbscribe commented on getting_started/step_by_step/your_first_game.rst
> +the other node button and create a
>  click on the other node button

This is the third scene we've created so far, so this seems unnecessary. At least title it consistently: "Other Node" button

2020-05-20 21:19 UTC, cbscribe commented on getting_started/step_by_step/your_first_game.rst
> +:ref:`Node <class_Node>` node as the root of the scene, it has a
"Node node" is redundant

2020-05-20 21:19 UTC, cbscribe commented on getting_started/step_by_step/your_first_game.rst
> +white circle as an icon and should be selected by default. Name
The "," should be the start of a new sentence.

> `Node` is the first node type in the list and has a white circle icon.

Note: it probably *won't* be selected by default if the reader has done any searching of the node list previously. I'd recommend removing that statement.

2020-05-21 03:05 UTC, skyace65 commented
Someone got confused and opened an issue so I figure we might as well clarify it. I've made the changes you suggested.

2020-05-21 13:05 UTC, mhilbrunner commented
I think this is okay to merge, but I don't have a strong opinion on this - I'll let @cbscribe decide whether the added complexity of the description is worth it to be more explicit, and to merge or close. :)

Thanks for your work!

2020-05-21 13:06 UTC, mhilbrunner approved these changes

2020-06-03 11:15 UTC, mhilbrunner commented
Having another looks, I changed my mind - I too don't see this as something that needs fixing, and it *is* very verbose. I'll close this, as there's been no consensus either way. Still, thanks for the contribution! :)

2020-06-03 11:15 UTC, closed without merging