Document differences between Bullet and GodotPhysics
godotengine/godot-docs pull request #3951
Opened 2020-08-31 21:17 UTC by skyace65

Adds a page to the physics section going over the known differences between Bullet and GodotPhysics. Closes #2161. These are not all the differences, only the ones that have been brought up in issues.

2020-08-31 21:19 UTC, Calinou requested changes

2020-08-31 21:19 UTC, Calinou commented on tutorials/physics/bullet_and_godotphysics_differences.rst
> +in how the physics engines function, and they will NOT always produce
```suggestion
in how the physics engines function, and they will **not** always produce
```

2020-08-31 21:19 UTC, Calinou commented on tutorials/physics/bullet_and_godotphysics_differences.rst
> +In Bullet physics the center of mass for RigidBody3D nodes is the center
```suggestion
In Bullet physics, the center of mass for RigidBody3D nodes is the center
```

2020-08-31 21:19 UTC, Calinou commented on tutorials/physics/bullet_and_godotphysics_differences.rst
> +of the node. In GodotPhysics the center of mass is the average of the
```suggestion
of the node. In GodotPhysics, the center of mass is the average of the
```

2020-08-31 21:23 UTC, skyace65 commented
Fixed.

2020-09-09 10:06 UTC, akien-mga commented on tutorials/physics/bullet_and_godotphysics_differences.rst
> +Bullet and GodotPhysics Differences
Don't use Title Case.

2020-09-09 10:34 UTC, AndreaCatania requested changes

2020-09-09 10:34 UTC, AndreaCatania commented on tutorials/physics/bullet_and_godotphysics_differences.rst
> +is significantly less strong in Bullet compared to GodotPhysics.
This is no more true, lately there was an update to fix it: https://github.com/godotengine/godot/pull/37314. It's also back ported to 3.2.x https://github.com/godotengine/godot/pull/39084

2020-09-09 17:04 UTC, madmiraal commented
Personally, I think this page is no longer needed. The two issues that drove the creation of #2161, were shown to be a limitation in Bullet physics' damping that, as @AndreaCatania has [pointed out](https://github.com/godotengine/godot-docs/pull/3951#discussion_r485507194), has since been addressed.

In general, I think that if there is a difference between the way Godot and Bullet physics behaves, it's more likely to be a bug that should be addressed. If there are multiple issues, we have tracker issues that are a better way to collate the information than a page in the documentation.

On the other hand, if there were genuine, significant differences between Godot and Bullet physics that a user could use to make an informed decision about which physics engine to use, then I would be in full support of this page.

Regarding the centre of gravity difference. The real issue is not that the centre of gravity is calculated differently, but that the centre of gravity or, more generally, the moment of inertia is not easily definable. See [#29099](https://github.com/godotengine/godot/issues/29099).

In short, I don't think we need an entire page that currently only points out that the centre of gravity may be different if an object has multiple shapes that are not centred. Information that I'm not sure many users would find useful, never mind use to make a decision about which physics engine to use.

2020-09-11 15:01 UTC, skyace65 commented
@akien-mga do you think this page is still necessary? Since damping is now consistent between Bullet and GodotPhysics there would only be one change to document, and it's already covered in the class reference.  And if not could you close issue #2161?

2020-09-11 15:31 UTC, closed without merging