Improve importing images page
godotengine/godot-docs pull request #3976
Opened 2020-09-07 01:00 UTC by skyace65

Removes the section at the beginning explaining that assets are imported now compared to older Godot versions. I've moved up the list of supported formats to the top of the page, it didn't make sense being in the middle of import settings. and the direct link to that has been removed. The link on the features page was the only one in the documentation.

2020-09-07 12:04 UTC, Calinou requested changes

2020-09-07 12:04 UTC, Calinou commented on getting_started/workflow/assets/importing_images.rst
> +This option only applies to svg files. It controls the scale of the svg image.
```suggestion
This option only applies to SVG files. It controls the scale of the SVG image. The default scale (1.0) will make the imported SVG match its original design scale.
```

2020-09-07 13:11 UTC, skyace65 commented
Fixed.

2020-09-09 10:44 UTC, merged

2020-09-09 10:44 UTC, akien-mga commented
Thanks!