Updated custom webexport to be more clear
godotengine/godot-docs pull request #4015
Opened 2020-09-15 07:58 UTC by BaseCrusher

Added a description of how to use external files after HTML export as well as a simple example of how to do this.

Correlates with this pull request :
https://github.com/godotengine/godot-docs/pull/2510

2020-09-15 08:05 UTC, BaseCrusher commented
Hmm, there seems to be an issue with my additions. Don't really know what is causing it though.

2020-09-15 08:08 UTC, akien-mga commented on getting_started/workflow/export/exporting_for_web.rst
> +		}, displayFailureNotice);
```suggestion
::

    Engine.load(MAIN_PACK)
    engine.preloadFile('$GODOT_BASENAME.js')
    engine.preloadFile('$GODOT_BASENAME.pck')
    engine.preloadFile('$GODOT_BASENAME.png')
    engine.preloadFile('$GODOT_BASENAME.wasm')
    engine.preloadFile('my_text.txt')
    engine.init()
    setStatusMode('indeterminate');
    engine.setCanvas(canvas);
    engine.start().then(() => {
    	setStatusMode('hidden');
    	initializing = true;
    }, displayFailureNotice);
```

2020-09-15 08:08 UTC, akien-mga commented on getting_started/workflow/export/exporting_for_web.rst
> +and replace the lines 250 to 255 with.
Line numbers will change, so hardcoding them in the doc is not a good idea.

2020-09-15 08:09 UTC, akien-mga commented on getting_started/workflow/export/exporting_for_web.rst
> +Use the default HTML page `/misc/dist/html/full-size.html <https://github.com/godotengine/godot/blob/master/misc/dist/html/full-size.html>`__. as a refrence
```suggestion
Use the default HTML page `misc/dist/html/full-size.html <https://github.com/godotengine/godot/blob/master/misc/dist/html/full-size.html>`__. as a reference 
```

2020-09-15 08:09 UTC, akien-mga commented on getting_started/workflow/export/exporting_for_web.rst
> +and replace the lines 250 to 255 with.
```suggestion
Here is an example of the part of the HTML page that needs to be modified.
Use the default HTML page `misc/dist/html/full-size.html <https://github.com/godotengine/godot/blob/master/misc/dist/html/full-size.html>`__
as a reference and replace the lines 250 to 255 with:
```

2020-09-15 08:46 UTC, BaseCrusher commented
Aight, so it's kinda embarassing for me. I've just taken a look into the Godot Docs. There is already a very good documentation for custom HTML export. I will just paste some example code there.

2020-09-15 08:52 UTC, akien-mga commented
Well we shouldn't copy paste existing documentation in other pages. If the documentation already exists, it just needs to be referred to where you think the link was missing.

You can use the `.. seealso::` directive to make a custom box that will refer users to extra documentation.

That being said there are already 6 references to `customizing_html5_shell` in that page, so maybe adding one is not necessary.

2020-09-15 08:58 UTC, BaseCrusher commented
Right, I've only inserted an example into the custom html export to be a litle bit more clearer. And reverted the changes on the plain html export.

2020-09-17 22:11 UTC, pycbouh requested changes
If we are adding an example to this section, then in the spirit of the article it should be localized to one particular problem. There seems to be too much code and I'm not sure what it is supposed to demonstrate exactly. Calls to `preloadFile` itself pretty self-explanatory, IMO. But maybe I'm not seeing the problem this example aims to cover.

We should also avoid using code that is not a part of the built-in API and is not defined in the example. Like calls to `setStatusMode` and `displayFailureNotice`.

2020-09-17 22:11 UTC, pycbouh commented on tutorials/platform/customizing_html5_shell.rst
> +::
Please use `.. code-block:: js` to allow proper syntax highlighting.

2020-09-18 13:42 UTC, Faless requested changes
I hope I helped clarifying it a bit.

2020-09-18 13:42 UTC, Faless commented on tutorials/platform/customizing_html5_shell.rst
> +    Engine.load(MAIN_PACK)
This should be `Engine.load(EXECUTABLE_NAME)`

2020-09-18 13:42 UTC, Faless commented on tutorials/platform/customizing_html5_shell.rst
> +    engine.preloadFile('my_text.txt')
This is wrong, you only need to preload the `pck` and your file (not the PNG, not the wasm, not the js).

Alternatively , you should be able to skip the `Engine.load(EXECUTABLE_NAME)`, `engine.preloadFile(MAIN_PACK)`, and `engine.init()` by using startGame:

```javascript
engine.preloadFile('my_text.txt').then(function() {
    engine.startGame(EXECUTABLE_NAME, MAIN_PACK).then(() => {
        setStatusMode('hidden');
        initializing = false;
    }, displayFailureNotice);
});
```

2020-09-22 08:26 UTC, BaseCrusher commented
Well, I just stumbled at this again a year after posting it on the original PR. 
Since at the time of posting there wasn't any explanation to how to custumize the loading behaviour for HTML, I wonted to add a small and quick description to how it is done. 
I have to admit that I'm not sure if the example is still needed. Though I think that for newcomers this might be helpful. Now, since I haven't done anything in Godot for a long time I don't know ho anything did change.

If there is no need fo this PR change you can just close it. 
I want to apologize for all this hassle. :(

2020-09-26 17:43 UTC, NathanLovato commented
@Faless would you include this example, once corrected, in this document? To know if we should request changes or close the PR.

@BaseCrusher No worries, we appreciate people getting out of their way to contribute to the project, even if a change doesn't make it in the docs. But let's see, I need someone else's input; I'm not familiar with web export.

2021-09-15 15:33 UTC, pycbouh commented
The API has since changed, and so have examples. I'll close this as outdated and lacking support, but if the current state of the article is missing any examples, feel free to open a new PR (but take the feedback given here into consideration).

2021-09-15 15:33 UTC, closed without merging