Make PerlinNoise3D accept scalars directly
godotengine/godot-docs pull request #4264
Opened 2020-10-13 16:12 UTC by Beuc

The current code requires creating and plugging a Scalar node just to enter the value "10" (see current screenshot); with this change, the node, like existing Godot nodes, can take the scalar value directly within the PerlinNoise3D Node.

2020-10-13 18:10 UTC, Chaosus commented
I think the offset param can be rid off too...

2020-10-15 05:29 UTC, Chaosus requested changes
I think it's fine but the screenshot in the original article should also be updated accordingly.

2020-10-16 15:34 UTC, Beuc commented
With this change, the screenshot will actually look the same with a scalar (or any other) node plugged to 'scale'.
It's different only if the user decides to set the variable within the node.

2020-10-16 15:42 UTC, Beuc commented
One issue however: the node doesn't seem to properly save the value for 'scale' if it's set directly within the node. The value is maintained while editing the project (including closing/reopening the scene), but the value is reset to 0 when closing the project and opening it again. Tested with Godot 3.2.3.

2020-10-16 16:46 UTC, Chaosus commented
> With this change, the screenshot will actually look the same with a scalar (or any other) node plugged to 'scale'.
> It's different only if the user decides to set the variable within the node.

Yeah, I thought you wanted to reflect it on the screenshot by disconnecting from the node. But if not - I think it's also fine.

> One issue, however: the node doesn't seem to properly save the value for 'scale' if it's set directly within the node. The value is maintained while editing the project (including closing/reopening the scene), but the value is reset to 0 when closing the project and opening it again. Tested with Godot 3.2.3.

Could you report this as an issue? - that would be more correct.

2020-10-16 16:46 UTC, Chaosus approved these changes

2020-10-16 18:03 UTC, Beuc commented
I can report the issue though I was wondering whether the issue is in Godot or from something missing in my patch.

2020-10-17 17:08 UTC, merged

2020-10-17 17:08 UTC, NathanLovato commented
Thanks!