Document hiDPI support in Multiple resolutions
godotengine/godot-docs pull request #4363
Opened 2020-11-13 17:32 UTC by Calinou

2020-11-14 11:07 UTC, Feniks-Gaming requested changes
Just one word missing and then it makes sense.

2020-11-14 11:07 UTC, Feniks-Gaming commented on tutorials/rendering/multiple_resolutions.rst
> +**Allow Hidpi** is only effective on Windows and macOS. It's ignored on all platforms.
It's ignored on all other platforms.

2020-11-14 13:03 UTC, Feniks-Gaming approved these changes

2020-11-18 02:46 UTC, skyace65 commented
This closes #1933

2020-11-27 22:03 UTC, merged

2020-11-27 22:03 UTC, NathanLovato commented
Thanks!