Change variable for Android SDK path
godotengine/godot-docs pull request #4407
Opened 2020-11-26 03:45 UTC by remtaine

The Gradle looks for "ANDROID_SDK_ROOT" and not "ANDROID_HOME" so I changed the path mentioned for clarity

2021-01-04 16:18 UTC, akien-mga commented
> The Gradle looks for "ANDROID_SDK_ROOT" and not "ANDROID_HOME" so I changed the path mentioned for clarity

Are you sure? Even Godot's own custom build workflow sets `ANDROID_HOME` for Gradle: https://github.com/godotengine/godot/blob/master/platform/android/export/export.cpp#L2422

2021-01-05 02:04 UTC, m4gr3d commented
@akien-mga `ANDROID_HOME` is [deprecated (but still supported for backward compatibility)](https://developer.android.com/studio/command-line/variables#envar), so it's safe to use either one.

2021-01-05 02:04 UTC, m4gr3d approved these changes

2021-01-05 02:07 UTC, m4gr3d requested changes
@remtaine There's one more location to update under the `Troubleshooting` section.

2021-01-05 02:09 UTC, m4gr3d commented
@akien-mga Is there a `label` to indicate this should be cherry-picked for the `3.2` docs as well?

2021-01-05 08:21 UTC, akien-mga commented
> @akien-mga Is there a `label` to indicate this should be cherry-picked for the `3.2` docs as well?

There used to be, but then we stop using it as I was merging the `master` branch in `3.2` regularly (reverting `master`-specific changes).
Now `master` and `3.2` have diverged too much in structure though so we'll have to go back to manually identifying candidates for cherry-picking.

2021-01-05 08:24 UTC, m4gr3d commented
The updated file seems to have the same structure in both `master` and `3.2` so it may be possible to cherry-pick here.
Otherwise @remtaine you may need to provide a similar backport for `3.2`.

2021-01-05 12:37 UTC, remtaine commented
> @remtaine There's one more location to update under the `Troubleshooting` section.

Okay! I changed that one as well now

2021-01-05 14:07 UTC, merged

2021-01-05 14:07 UTC, akien-mga commented
Thanks! And congrats for your first merged Godot contribution :tada: