Mention the ProjectSettings globalize/localize methods in Data paths
godotengine/godot-docs pull request #4439
Opened 2020-12-06 10:58 UTC by Calinou

This closes https://github.com/godotengine/godot-docs/issues/4409.

2020-12-07 10:31 UTC, Feniks-Gaming requested changes
Could we explain what is a benefit in doing so and give example of what will the path look before and after to make it easier to understand. For example I have no idea why I would want to do that.

2020-12-09 16:57 UTC, Calinou commented
@Feniks-Gaming Done, I added an example use case for `ProjectSettings.globalize_path()`. I can't think of an use case for `ProjectSettings.localize_path()` though (at least right now).

2020-12-10 12:37 UTC, Feniks-Gaming approved these changes

2021-01-04 15:58 UTC, akien-mga approved these changes

2021-01-04 15:58 UTC, merged

2021-01-04 15:58 UTC, akien-mga commented
Thanks!