Document the ternary operator in Shading language
godotengine/godot-docs pull request #4440
Opened 2020-12-06 11:03 UTC by Calinou

This closes https://github.com/godotengine/godot-docs/issues/4438.

2020-12-06 17:15 UTC, clayjohn approved these changes

2020-12-08 13:05 UTC, Feniks-Gaming requested changes

2020-12-08 13:05 UTC, Feniks-Gaming commented on tutorials/shaders/shader_reference/shading_language.rst
> +        case 1: // fall-through
Can we explain what we mean by fall-through what does it do?

2020-12-08 13:05 UTC, Feniks-Gaming commented on tutorials/shaders/shader_reference/shading_language.rst
> +    // `do while`. Like `while`, but always runs at least once.
I don't really understand how while and do while differ from this could we have example of code for both illustrating a difference

2020-12-08 16:19 UTC, Feniks-Gaming approved these changes
Thanks. It's much clearer now

2020-12-25 09:21 UTC, merged

2020-12-25 09:21 UTC, Chaosus commented
TY, merged