Fix C# code for changing scene
godotengine/godot-docs pull request #4523
Opened 2021-01-05 23:20 UTC by humboldt123

This pull request aims to fix an issue in the C# example code of "Changing Scenes Manually".

Previously the code called the `addChild()` method with a `PackedScene`; however `addChild()` accepts a Node.

This pull request changes the Type of `simultaneousScene` to a `Node` while fixing a typo in the way the `Instance()` method was called.

2021-01-05 23:33 UTC, humboldt123 commented
Later in the file; it is also possible to change `GetRoot()` to `Root` but I do not know if this is an intentional styling choice.

2021-01-06 22:38 UTC, aaronfranke requested changes

2021-01-06 22:38 UTC, aaronfranke commented on tutorials/scripting/change_scenes_manually.rst
> +        simultaneousScene = ((PackedScene) ResourceLoader.Load("res://levels/level2.tscn")).Instance();
```suggestion
        simultaneousScene = ResourceLoader.Load<PackedScene>("res://levels/level2.tscn").Instance();
```

2021-01-07 01:58 UTC, aaronfranke approved these changes
This should be squashed, but the code is good.

2021-01-07 13:28 UTC, merged

2021-01-07 13:28 UTC, akien-mga commented
Thanks!