Add note about content guidelines in writing guidelines page
godotengine/godot-docs pull request #4547
Opened 2021-01-16 17:55 UTC by skyace65

Adds a note to the beginning of the writing guidelines page about the content guidelines. Closes #4066

2021-01-16 20:18 UTC, pycbouh commented
I'm not entirely sure what would be the best place for this note. Maybe some clean up is required in the article itself to make that cross-link more fitting. I guess for the time being we can add it like this.

2021-01-16 20:18 UTC, pycbouh approved these changes

2021-01-16 20:41 UTC, Calinou requested changes

2021-01-16 20:41 UTC, Calinou commented on community/contributing/docs_writing_guidelines.rst
> +    `content guidelines <doc_content_guidelines>`__.
```suggestion
.. seealso::

    See the `content guidelines <doc_content_guidelines>`__ for information
    on the types of documentation you can write.
```

2021-01-16 20:47 UTC, skyace65 commented
Huh, I didn't even know we had a "see also" thing. Fixed.

2021-01-21 17:37 UTC, merged

2021-01-21 17:38 UTC, NathanLovato commented
Thanks!

In general, I think it's good to cross-ref in different places so the users has multiple paths to stumble pages they're interested in, as it depends a lot on how they land on the docs and their browsing habits.