Added C# variant tabs to GD code tabs.
godotengine/godot-docs pull request #4662
Opened 2021-02-18 14:14 UTC by VinnNo

Added C# code tab to accomplish the same functionality found in the GDScript example. Removed the GDScript tab for the interpolation pseudo code; it's not actually GDScript, or C# for that matter, but is probably still useful as a block.

2021-02-23 22:29 UTC, aaronfranke requested changes

2021-02-23 22:29 UTC, aaronfranke commented on tutorials/math/interpolation.rst
> +        t += (float)(delta * 0.4);
```suggestion
        t += delta * 0.4f;
```

2021-02-23 22:29 UTC, aaronfranke commented on tutorials/math/interpolation.rst
> +        Position2D B = (Position2D)GetNode("B");
```suggestion
        Position2D A = GetNode<Position2D>("A");
        Position2D B = GetNode<Position2D>("B");
```

2021-02-23 22:29 UTC, aaronfranke commented on tutorials/math/interpolation.rst
> +        Position3D P2 = (Position3D)GetNode("Position2");
```suggestion
        Position3D P1 = GetNode<Position3D>("Position1");
        Position3D P2 = GetNode<Position3D>("Position2");
```

2021-02-23 22:29 UTC, aaronfranke commented on tutorials/math/interpolation.rst
> +        CSGMesh Monkey = (CSGMesh)GetNode("Monkey");
```suggestion
        CSGMesh Monkey = GetNode<CSGMesh>("Monkey");
```

2021-02-23 22:29 UTC, aaronfranke commented on tutorials/math/interpolation.rst
> +    const float FOLLOW_SPEED = 4.0f;
```suggestion
    public const float FollowSpeed = 4.0f;
```

2021-02-23 22:29 UTC, aaronfranke commented on tutorials/math/interpolation.rst
> +        var MousePos = GetLocalMousePosition();
```suggestion
        Vector2 mousePos = GetLocalMousePosition();
```

2021-02-23 22:29 UTC, aaronfranke commented on tutorials/math/interpolation.rst
> +        Sprite MySprite = (Sprite)GetNode("Sprite");
```suggestion
        Sprite MySprite = GetNode<Sprite>("Sprite");
```

2021-02-23 22:29 UTC, aaronfranke commented on tutorials/math/interpolation.rst
> +        MySprite.Position = MySprite.Position.LinearInterpolate(MousePos, delta * FOLLOW_SPEED);
```suggestion
        MySprite.Position = MySprite.Position.LinearInterpolate(mousePos, delta * FollowSpeed); 
```

2021-09-09 11:33 UTC, mhilbrunner commented
Same as https://github.com/godotengine/godot-docs/pull/4666, this has been open for quite a while with unadressed feedback.

Closing for now and marking as salvageable, as the content is still wortwhile, it just need to be updated.

Feel free to request a reopen or to submit a new PR, and thanks for contributing!

2021-09-09 11:33 UTC, closed without merging