Added C# variant tabs to GD example code tabs.
godotengine/godot-docs pull request #4663
Opened 2021-02-18 17:00 UTC by VinnNo

Added C# example code tabs to accomplish the same functionality found in the GDScript tab example.

2021-02-18 17:16 UTC, VinnNo reviewed
Removed a randomly added "Particle2D" in the Quadratic_Bezier() inputs

2021-02-23 22:36 UTC, aaronfranke requested changes

2021-02-23 22:36 UTC, aaronfranke commented on tutorials/math/beziers_and_curves.rst
> +    public Vector2 Quadratic_Bezier(Vector2 p0, Vector2 p1, Vector2 p2, float t)
```suggestion
    public Vector2 QuadraticBezier(Vector2 p0, Vector2 p1, Vector2 p2, float t)
```

2021-02-23 22:36 UTC, aaronfranke commented on tutorials/math/beziers_and_curves.rst
> +        var q1 = p1.LinearInterpolate(p2, t);
`linear_interpolate` and `LinearInterpolate` are `lerp` and `Lerp` in the master branch of Godot (what will become Godot 4.0). The GDScript example also needs updating, which would be appreciated :)

```suggestion
        Vector2 q0 = p0.Lerp(p1, t);
        Vector2 q1 = p1.Lerp(p2, t);
```

2021-02-23 22:36 UTC, aaronfranke commented on tutorials/math/beziers_and_curves.rst
> +        var r = q0.LinearInterpolate(q1, t);
```suggestion
        Vector2 r = q0.Lerp(q1, t);
```

2021-02-23 22:36 UTC, aaronfranke commented on tutorials/math/beziers_and_curves.rst
> +    public Vector2 Cubic_Bezier(Vector2 p0, Vector2 p1, Vector2 p2, Vector2 p3, float t)
```suggestion
    public Vector2 CubicBezier(Vector2 p0, Vector2 p1, Vector2 p2, Vector2 p3, float t)
```

2021-02-23 22:36 UTC, aaronfranke commented on tutorials/math/beziers_and_curves.rst
> +        var q2 = p2.LinearInterpolate(p3, t);
```suggestion
        Vector2 q0 = p0.Lerp(p1, t);
        Vector2 q1 = p1.Lerp(p2, t);
        Vector2 q2 = p2.Lerp(p3, t);
```

2021-02-23 22:36 UTC, aaronfranke commented on tutorials/math/beziers_and_curves.rst
> +        var r1 = q1.LinearInterpolate(q2, t);
```suggestion
        Vector2 r0 = q0.Lerp(q1, t);
        Vector2 r1 = q1.Lerp(q2, t);
```

2021-02-23 22:36 UTC, aaronfranke commented on tutorials/math/beziers_and_curves.rst
> +        var s = r0.LinearInterpolate(r1, t);
```suggestion
        Vector2 s = r0.Lerp(r1, t);
```

2021-02-23 22:36 UTC, aaronfranke commented on tutorials/math/beziers_and_curves.rst
> +        var s = r0.LinearInterpolate(r1, t);
```suggestion
        Vector2 q0 = p0.Lerp(p1, t);
        Vector2 q1 = p1.Lerp(p2, t);
        Vector2 q2 = p2.Lerp(p3, t);
        
        Vector2 r0 = q0.Lerp(q1, t);
        Vector2 r1 = q1.Lerp(q2, t);
        
        Vector2 s = r0.Lerp(r1, t);
```

2021-02-23 22:36 UTC, aaronfranke commented on tutorials/math/beziers_and_curves.rst
> +        Position = Cubic_Bezier(p0, p1, p2, p3, t)
```suggestion
        Position = CubicBezier(p0, p1, p2, p3, t)
```

2021-02-23 22:36 UTC, aaronfranke commented on tutorials/math/beziers_and_curves.rst
> +    float t = 0.0;
```suggestion
    float t = 0.0f;
```

2021-02-23 22:36 UTC, aaronfranke commented on tutorials/math/beziers_and_curves.rst
> +    float t = 0.0;
```suggestion
    float t = 0.0f;
```

2021-02-23 22:36 UTC, aaronfranke commented on tutorials/math/beziers_and_curves.rst
> +    public override void _Process(float delta)
Since delta is unused, we can prefix it with an underscore.

```suggestion
    public override void _Process(float _delta)
```

2021-02-23 22:42 UTC, aaronfranke requested changes

2021-02-23 22:42 UTC, aaronfranke commented on tutorials/math/beziers_and_curves.rst
> +    }
You are missing `t += delta` from the GDScript example.

2021-09-09 11:32 UTC, mhilbrunner commented
Sames as https://github.com/godotengine/godot-docs/pull/4666, closing this as it has unaddressed feedback and is open for quite some time.

It's still salvageable and would be good to have though, so feel free to address those and requets a reopen or to submit a new PR.

2021-09-09 11:32 UTC, closed without merging