Update the "Customizing the HTML5 Shell" page.
godotengine/godot-docs pull request #4748
Opened 2021-03-12 17:12 UTC by Faless

Reflecting new changes in master, and upcoming in `3.2.4`.

See godotengine/godot-proposals#2182 and it's final implementation godotengine/godot#46200 for reference.

2021-03-12 17:55 UTC, Calinou requested changes

2021-03-12 17:55 UTC, Calinou commented on tutorials/platform/customizing_html5_shell.rst
>  When handling the engine output keep in mind, that it may not be desirable to print it out in the
```suggestion
When handling the engine output, keep in mind that it may not be desirable to print it out in the
```

2021-03-12 17:56 UTC, Calinou commented on tutorials/platform/customizing_html5_shell.rst
> +code. This process consists of three steps, though as shown most of them can be skipped depending on
```suggestion
code. This process consists of three steps, but as shown here, most of them can be skipped depending on
```

2021-03-12 17:56 UTC, Calinou commented on tutorials/platform/customizing_html5_shell.rst
> +how much customization is needed (or be left to a default behavior).
```suggestion
how much customization is needed.
```

2021-03-12 17:57 UTC, Calinou approved these changes
Thanks!

2021-03-12 17:59 UTC, merged

2021-04-21 13:03 UTC, akien-mga commented
This was cherry-picked via #4798.