Remove duplicate setup instructions from android custom build page
godotengine/godot-docs pull request #4869
Opened 2021-04-25 17:37 UTC by skyace65

The exporting for android page already covers the information that I've removed from the custom builds page, and the custom builds page now tells you what you need to do from the setup page before making a custom build.

This makes the documentation significantly easier to maintain as we're not working with two different sets of setup instructions. I know we've had issues in the past with the two pages not giving the same information. If this is good to merge I'll make another PR for 3.3 branch so it can get added to stable. Though I want to close some other android issues with PRs before stable gets updated.

Closes #3469, closes #3470, closes #3689

2021-04-25 19:57 UTC, Calinou requested changes

2021-04-25 19:57 UTC, Calinou commented on tutorials/export/android_custom_build.rst
> +up to "Setting it up in Godot." After doing that follow the steps below.
```suggestion
Configuring the custom build is a fairly straightforward process. But first,
you need to follow the steps in :ref:`exporting for android<doc_exporting_for_android>`
up to **Setting it up in Godot**. After doing that, follow the steps below.
```

2021-04-26 01:42 UTC, skyace65 commented
Fixed

2021-04-26 14:48 UTC, m4gr3d approved these changes

2021-04-26 14:50 UTC, merged

2021-04-26 14:51 UTC, akien-mga commented
Thanks!

2021-04-26 14:56 UTC, akien-mga commented
Cherry-picked for 3.3 (not 3.2 as I think the instructions do differ there).

2021-04-26 23:36 UTC, skyace65 commented
@akien-mga can you cherry pick this one since the exporting pages are in a different location? If you need me to open a second PR for 3.3 I can do that.

2021-04-27 08:01 UTC, akien-mga commented
As I wrote above I cherry-picked it already.