Implemented Algolia search
godotengine/godot-docs pull request #4884
Opened 2021-04-29 19:07 UTC by leroy

Implements Algolia search as discussed in #4461

2021-04-29 19:35 UTC, Calinou requested changes

2021-04-29 19:35 UTC, Calinou commented on conf.py
> +# if not os.getenv("SPHINX_NO_SEARCH"):
Please remove this code entirely instead of commenting it out.

2021-04-29 19:35 UTC, Calinou commented on conf.py
> +    # extensions.append("sphinx_search.extension")
Same as above.

2021-05-14 19:31 UTC, Calinou commented on _static/css/algolia.css
> +}
```suggestion
}

```

2021-06-12 15:49 UTC, leroy commented
@Calinou

Hey :)

Do you need me to do anything to get this PR merged?

2021-06-12 17:16 UTC, Calinou commented
@leroy There are merge conflicts to solve in `requirements.txt`. Apologies for the delay.

2021-06-13 14:28 UTC, leroy commented
Hey no worries at all. I've resolved the merge conflicts.

2021-06-13 18:21 UTC, Calinou approved these changes
Thanks!

2021-06-13 18:21 UTC, merged

2021-06-13 20:10 UTC, Calinou commented
It seems to work on the [`latest` branch](docs.godotengine.org/en/latest/):

![image](https://user-images.githubusercontent.com/180032/121820589-079eb600-cc94-11eb-860b-920174ac5a02.png)

There are some things we need to improve still:

- Pressing the <kbd>Enter</kbd> key while the field is empty shouldn't do anything, since it will redirect you to a standard search page with no results found.
- `ref` badges should be placed on the same line as the page name (at the left of the page name), rather than on a separate line.
- There should be a dark theme when the documentation uses the dark theme as well (defined via CSS' `prefers-color-scheme: dark` media query).