Update android_in_app_purchases.rst
godotengine/godot-docs pull request #5104
Opened 2021-07-19 18:44 UTC by avnerh1

2021-07-19 18:46 UTC, avnerh1 commented
- Added an example of using ``_on_purchases_updated``, which is the right way to handle the result of `payment.purchase()`
- Added check for `purchase.purchase_state`
- Added some info about consuming a product and about using `queryPurchases()`

2021-07-25 16:47 UTC, troy-lamerton commented
Looks good to me. Checking the purchase state is essential which is the main thing added.

2021-07-26 18:18 UTC, m4gr3d commented
cc @timoschwarzer

2021-07-27 08:53 UTC, timoschwarzer requested changes
Thank you! Only some small changes :)

2021-07-27 08:53 UTC, timoschwarzer commented on tutorials/platform/android/android_in_app_purchases.rst
> +            if purchase.sku == "my_iap_item" and purchase.purchase_state==1:
```suggestion
            if purchase.sku == "my_iap_item" and purchase.purchase_state == 1:
```

2021-07-27 08:53 UTC, timoschwarzer commented on tutorials/platform/android/android_in_app_purchases.rst
> +                if !purchase.is_acknowledged:
```suggestion
                if not purchase.is_acknowledged:                                        
```

2021-07-27 08:53 UTC, timoschwarzer commented on tutorials/platform/android/android_in_app_purchases.rst
> +            if purchase.purchase_state==1: # 1 means "purchased"
```suggestion
            if purchase.purchase_state == 1: # 1 means "purchased", see https://developer.android.com/reference/com/android/billingclient/api/Purchase.PurchaseState#constants_1
```

2021-07-27 08:53 UTC, timoschwarzer commented on tutorials/platform/android/android_in_app_purchases.rst
> +                # enable_premium(purchase.sku) # unlock paid content, add coins, save token on server, etc.
```suggestion
                # enable_premium(purchase.sku) # unlock paid content, add coins, save token on server, etc. (you have to implement enable_premium yourself)
```

2021-07-27 08:53 UTC, timoschwarzer commented on tutorials/platform/android/android_in_app_purchases.rst
> +            if purchase.sku == "my_consumable_iap_item" and purchase.purchase_state==1:
```suggestion
            if purchase.sku == "my_consumable_iap_item" and purchase.purchase_state == 1:
```

2021-07-27 18:59 UTC, mhilbrunner approved these changes

2021-07-27 18:59 UTC, mhilbrunner commented on tutorials/platform/android/android_in_app_purchases.rst
> +
```suggestion

```

2021-07-27 18:59 UTC, mhilbrunner commented on tutorials/platform/android/android_in_app_purchases.rst
> +
```suggestion

```

2021-07-27 19:07 UTC, mhilbrunner commented on tutorials/platform/android/android_in_app_purchases.rst
> +::
```suggestion

Then, wait for the ``_on_purchases_updated`` callback and handle the purchase result:

::
```

2021-07-27 19:12 UTC, merged

2021-07-27 19:13 UTC, mhilbrunner commented
Merged. Thanks for this, and congrats on your first contribution to the Godot docs! :)

Small note: In future Pull Requests, please use clear commit messages instead of the autogenerated default.

2021-07-28 05:48 UTC, avnerh1 commented
> Merged. Thanks for this, and congrats on your first contribution to the Godot docs! :)
> 
> Small note: In future Pull Requests, please use clear commit messages instead of the autogenerated default.

Thank you!