Fix csharp code in using_kinematic_body_2d.rst
godotengine/godot-docs pull request #5173
Opened 2021-08-15 12:00 UTC by berightben

Match csharp code with gdscript code in the code-tab collider example.

2021-08-15 17:51 UTC, berightben commented
I add another commit to fix typo.

2021-09-09 11:16 UTC, mhilbrunner commented
@paulloz Any chance you can give this a look? :)

2021-09-09 11:32 UTC, paulloz requested changes

2021-09-09 11:32 UTC, paulloz commented on tutorials/physics/using_kinematic_body_2d.rst
> +        GD.Print("I collided with ", collision.Collider.Name);
```suggestion
        GD.Print("I collided with ", ((Node)collision.Collider).Name);
```

`KinematicCollision.Collider` is a `Godot.Object` which doesn't define `Name`.

2021-09-09 11:32 UTC, paulloz commented on tutorials/physics/using_kinematic_body_2d.rst
> +        GD.Print("I collided with ", collision.Collider.Name);
```suggestion
        GD.Print("I collided with ", ((Node)collision.Collider).Name);
```

Same as above.

2021-09-09 11:36 UTC, paulloz commented
Also, I'd prefer to see actual types (`KinematicCollision`) instead of `var` in these situations in the doc. As it's meant to be read on a website (and not in an IDE where you'd have Intellisense and all), it would be easier for the reader to know what type variables are.  
Though it doesn't feel right to block that particular PR for this, as `var` is used extensively in the docs already 🤔

2021-11-08 11:54 UTC, berightben commented
> Also, I'd prefer to see actual types (`KinematicCollision`) instead of `var` in these situations in the doc. As it's meant to be read on a website (and not in an IDE where you'd have Intellisense and all), it would be easier for the reader to know what type variables are. Though it doesn't feel right to block that particular PR for this, as `var` is used extensively in the docs already thinking

I think it is good to mention both options available, maybe in the introduction of csharp. 
It is safe to go with what you recommended, to teach type safety. But maybe in another PR? Maybe C# maintainer can discussed it separately.

2022-04-29 11:21 UTC, merged

2022-04-29 11:21 UTC, akien-mga commented
Thanks!

2022-04-29 11:44 UTC, akien-mga commented
Cherry-picked for 3.4.