Fix sub resource ID formatting in Object Class
godotengine/godot-docs pull request #5175
Opened 2021-08-15 23:12 UTC by hpnrep6

## Before

![Screenshot from 2021-08-15 19-10-09](https://user-images.githubusercontent.com/57055412/129495479-8bace098-fb4e-4e66-8520-e1abc59d4ab0.png)

## After

![Screenshot from 2021-08-15 19-08-54](https://user-images.githubusercontent.com/57055412/129495481-3c5a18c2-c88c-4f65-99e0-2ff88515e745.png)

2021-08-15 23:23 UTC, Calinou requested changes
Thanks!

2021-08-15 23:23 UTC, Calinou commented on development/cpp/object_class.rst
> +"\res://someresource.res::1". This also helps to cache them when loaded.
I'd suggest using an inline code block instead:

```suggestion
``res://someresource.res::1``. This also helps to cache them when loaded.
```

2021-08-16 01:36 UTC, hpnrep6 commented
Applied the changes!

2021-08-16 02:23 UTC, Calinou approved these changes
Thanks!

Cherry-picked to the `3.4`, `3.3`, `stable` and `3.2` branches.

2021-08-16 02:38 UTC, merged