Update configuring android studio page
godotengine/godot-docs pull request #5182
Opened 2021-08-19 00:16 UTC by skyace65

Updates the configuring android studio page with a new screenshot (went through png compression). minor update to the instructions. Also a minor fix, android studio isn't a JetBrains IDE, it's based on JetBrains Intellij IDE.

2021-08-19 01:14 UTC, pycbouh requested changes

2021-08-19 01:14 UTC, pycbouh commented on development/cpp/configuring_an_ide/android_studio.rst
> +IDE for Android development based on `Intellij <https://www.jetbrains.com/>`__.
Well, if we still link to the JetBrains website, it should also be okay to mention them by name. Android Studio *is* developer by both JetBrains and Google, so this statement wasn't wrong.

And if we were to mention the parent product, it's *IntelliJ IDEA*, not *Intellij*.

2021-08-19 01:55 UTC, skyace65 commented
I tweaked the description, better?

2021-08-19 14:58 UTC, pycbouh requested changes
Yes, but still a couple of nitpicks.

2021-08-19 14:58 UTC, pycbouh commented on development/cpp/configuring_an_ide/android_studio.rst
> +IDE for Android development made by google and `JetBrains <https://www.jetbrains.com/>`_,
```suggestion
IDE for Android development made by `Google <https://about.google/>`_ and `JetBrains <https://www.jetbrains.com/>`_.
```

Proper capitalization and we can still link to Google (we do link to Microsoft in other articles).

2021-08-19 14:58 UTC, pycbouh commented on development/cpp/configuring_an_ide/android_studio.rst
> +and based on `Intellij IDEA <https://www.jetbrains.com/idea/>`__. It has a
```suggestion
It's based on `IntelliJ IDEA <https://www.jetbrains.com/idea/>`__ and has a
```

2021-08-20 01:54 UTC, skyace65 commented
Fixed.

2021-08-20 09:09 UTC, pycbouh approved these changes

2021-08-22 14:22 UTC, merged

2021-08-22 14:22 UTC, mhilbrunner commented
Thank you :)