[WIP] Add 3D Particles Documentation
godotengine/godot-docs pull request #5535
Opened 2022-01-20 21:16 UTC by and-rad

This adds a new page to the documentation, covering 3D particle systems.

This is a **WIP** PR, the documentation is not yet complete. I'm putting it up already because I'd like someone to take a look at it and tell me if it's going in the right direction.

2022-06-01 10:52 UTC, clayjohn reviewed
You are definitely on the right track! This is looking great so far. I'm looking forward seeing to the rest of your progress

2022-07-18 12:28 UTC, and-rad commented
Small heads up: It might look like I'm not making any progress lately, but that's just me waiting for 4.0 to become a little more feature-complete. I've had to redo some screenshots and gifs multiple times already since I started writing the docs because names and features have changed in the meantime. And with https://github.com/godotengine/godot-proposals/issues/3588 probably getting implemented, I'll have to reorganize a lot of what's already written.

So in an effort to not have to do too many do-overs, I'm keeping the particle docs on the back burner, but I'll pick up the pace again as soon as 4.0 nears RC status.

2022-07-18 18:52 UTC, clayjohn commented
@and-rad Sounds great! Thanks for letting us know. I look forward to when you return to this PR :)

2022-07-20 13:23 UTC, and-rad commented
Gonna link https://github.com/godotengine/godot/issues/61014 here. Even though it doesn't currently work, I have documented the feature as if it did. I expect it'll be fixed in time for the 4.0 release.

2023-03-13 16:46 UTC, Calinou commented
> Gonna link [godotengine/godot#61014](https://github.com/godotengine/godot/issues/61014) here. Even though it doesn't currently work, I have documented the feature as if it did. I expect it'll be fixed in time for the 4.0 release.

This wasn't fixed for 4.0's release, so I suggest adding a ``warning`` block to mention that the feature won't work yet.

2023-03-13 17:03 UTC, Calinou requested changes
The text is very good and complete, thanks a lot for going through this effort!

There are some changes that should be made to page and reference names though. Page names should use `snake_case` as per convention, and reference names should follow the file names (with parents included if there's possible ambiguity with other pages in the documentation).

Some page names should also be changed for better SEO, and so that they make more sense when viewed individually.

Here's a list of proposed changes (old → new):

- `complexshapes.rst` → `complex_shapes.rst`
- `doc_complexemissionshapes3d` → `doc_3d_particles_complex_shapes`
- `creation.rst` → `creating_a_3d_particle_system.rst`
- `doc_particlecreation3d` → `doc_creating_3d_particle_system`
- `doc_particles3d` → `doc_3d_particles`
- `doc_particleprocessmaterial3d` → `doc_process_material_properties`
- `doc_particleattractors3d` → `doc_3d_particle_attractors` (also rename the page to "3D particle attractors", and add a note that 2D particle attractors aren't implemented yet)
- `doc_particlecollision3d` → `doc_particle_collision_3d`
- `doc_particleproperties3d` → `doc_particle_properties_3d`
- `doc_subemitters3d` → `doc_subemitters_3d` (also rename the page to "Particle sub-emitters" with a hyphen)
- `doc_particletrails3d` → `doc_particle_trails_3d`
- `doc_particleturbulence3d` → `doc_particle_turbulence_3d` (also rename the page to "Particle turbulence"

2023-03-14 11:34 UTC, and-rad commented
Done. I deviated from some of your suggestions when I felt it would improve consistency, but I think I got the important parts right.

2023-04-17 13:18 UTC, Calinou approved these changes
Thanks a ton!

2023-04-30 12:22 UTC, Calinou commented on tutorials/3d/particles/turbulence.rst
> +Once enabled, you have access to all the turbulence properties.
```suggestion
Once enabled, you have access to all the turbulence properties.

.. warning::

	Turbulence has a high performance cost on the GPU. Only enable turbulence on a few particle systems on screen at most. Using turbulence is not recommended when targeting mobile/web platforms.
```

2023-04-30 12:24 UTC, Calinou commented
I've amended a PR to document performance caveats of turbulence as per https://github.com/godotengine/godot/issues/76501.

2023-04-30 12:25 UTC, Calinou approved these changes
Thanks a ton!

2023-04-30 12:25 UTC, merged