Update tutorials: VisualServer to RenderingServer
godotengine/godot-docs pull request #5581
Opened 2022-02-05 01:28 UTC by Sauermann

Update references from `VisualServer` to `RenderingServer`.
Remove note about `texture_set_shrink_all_x2_on_set_data`, since it is no longer exposed in RenderingServer.

2022-02-05 15:39 UTC, Calinou commented on tutorials/rendering/multiple_resolutions.rst
> +will increase memory usage which may be problematic on low-end mobile devices.
```suggestion

To resolve this, you can enable mipmaps on all your 2D textures. However, enabling mipmaps
will increase memory usage which may be problematic on low-end mobile devices.
```

2022-02-05 15:42 UTC, Sauermann commented on tutorials/rendering/multiple_resolutions.rst
> +will increase memory usage which may be problematic on low-end mobile devices.
Thanks for the improvement

2022-02-09 19:09 UTC, mhilbrunner requested changes

2022-02-09 19:09 UTC, mhilbrunner commented on tutorials/3d/procedural_geometry/arraymesh.rst
> +values can be found in the classref for :ref:`RenderingServer <renderingserver>` under :ref:`ArrayFormat <enum_renderingserver_arrayformat>`.
```suggestion
values can be found in the classref for :ref:`RenderingServer <class_renderingserver>` under :ref:`ArrayFormat <enum_renderingserver_arrayformat>`.
```

2022-02-09 19:13 UTC, Sauermann commented on tutorials/3d/procedural_geometry/arraymesh.rst
> +values can be found in the classref for :ref:`RenderingServer <renderingserver>` under :ref:`ArrayFormat <enum_renderingserver_arrayformat>`.
Thanks for the correction

2022-02-10 10:06 UTC, mhilbrunner approved these changes

2022-02-10 10:07 UTC, merged

2022-02-10 10:07 UTC, mhilbrunner commented
Thank you!