Update project_manager.rst
godotengine/godot-docs pull request #5602
Opened 2022-02-13 14:37 UTC by jeancallisti

- Clarified that the "Project manager" is sometimes called "Projects list"
- Pointed out that the screenshot is obsolete and that the "Templates" tab has a new name.

2022-02-13 15:17 UTC, pycbouh requested changes

2022-02-13 15:17 UTC, pycbouh commented on tutorials/editor/project_manager.rst
> +Note : In more recent versions of Godot, the "Tempates" tab has been renamed "Asset Library Projects".
The docs are for the most recent version, so the appropriate fix is to update the screenshot.

2022-02-13 15:17 UTC, pycbouh commented on tutorials/editor/project_manager.rst
> +You can also reach that screen from within Godot by selecting menu entry Project-->Quit to Project List
```suggestion
You can also reach that screen from within Godot editor by selecting ``Project -> Quit to Project List`` from the top menu.
```

Although I'm not sure this is the best place to mention it. Feels awkward.

2022-04-29 09:46 UTC, akien-mga commented
Closing as this is not the proper way to update this as pointed out by review comments, and didn't get updated further.

2022-04-29 09:46 UTC, closed without merging