Document 3D navigation server in Godot 3.5
godotengine/godot-docs pull request #5800
Opened 2022-05-04 00:32 UTC by skyace65

Documents the new 3D navigation server in Godot 3.5. It's a copy and paste of the 4.0 with some minor changes for 3.5. The old method is still documented, but it is stated that it will be removed in Godot 4.

2022-05-04 09:17 UTC, mhilbrunner requested changes
Looks good, two minor things, besides that should be ready to merge :) Good work!

2022-05-04 09:17 UTC, mhilbrunner commented on tutorials/navigation/real_time_navigation_3d.rst
> +define what parts of the world that can be navigated around by navigation
```suggestion
define parts of the world that can be navigated around by navigation
```

2022-05-04 09:17 UTC, mhilbrunner commented on tutorials/navigation/real_time_navigation_3d.rst
> +to each other. Additionally A baked navmesh can be moved at runtime and
```suggestion
to each other. Additionally a baked navmesh can be moved at runtime and
```

2022-05-04 12:32 UTC, skyace65 commented
Fixed.

2022-05-04 14:24 UTC, mhilbrunner approved these changes

2022-05-05 13:46 UTC, merged

2022-05-05 13:46 UTC, mhilbrunner commented
Thanks for helping filling out the 3.5 docs! 🎉 Good work :)