Add missing C# samples for the "Inspector plugins" page
godotengine/godot-docs pull request #5829
Opened 2022-05-20 18:27 UTC by seclerp

Adding missing C# samples for the "Plugins > Inspector plugins" page makes it simpler to get started using the C# codebase.

The code below is dev-tested.

2022-06-01 00:08 UTC, raulsntos requested changes
Thanks for the contribution. The C# code needs to be surrounded by `#if TOOLS` (see https://github.com/godotengine/godot-docs/blob/dc20b238e3256a5a6abbf5b1bf6c0f5cf035c6e1/tutorials/plugins/editor/making_plugins.rst for an example) because editor classes (like `EditorPlugin`) are not available on exported games.

2022-06-01 00:11 UTC, raulsntos commented on tutorials/plugins/editor/inspector_plugins.rst
> +            _propertyControl.Connect("pressed", this, nameof(OnButtonPressed));
I forgot this is `master`'s documentation. The connecting syntax has changed and should now be:

```suggestion
            _propertyControl.Pressed += OnButtonPressed;
```

2022-06-01 15:48 UTC, raulsntos approved these changes

2022-06-08 11:22 UTC, merged

2022-06-08 11:22 UTC, akien-mga commented
Thanks!

2022-06-08 11:25 UTC, akien-mga commented
Cherry-picked for 3.4 and 3.5.