update pull request template to be similar to godotengine/godot
godotengine/godot-docs pull request #5909
Opened 2022-07-04 05:51 UTC by nathanfranke

\

2022-07-04 06:25 UTC, aaronfranke approved these changes
See this PR in the main repo: https://github.com/godotengine/godot/pull/62486

2022-07-04 09:34 UTC, YuriSizov requested changes
We don't have 3.x here, you must use a specific version branch, the one that corresponds to the latest applicable version. So the text must be adjusted.

2022-07-04 17:18 UTC, YuriSizov requested changes
Slight adjustment and another note worth pointing out, and then I think this is fine.

2022-07-04 17:18 UTC, YuriSizov commented on .github/PULL_REQUEST_TEMPLATE.md
> +PRs can target other branches if the same change was done in `master`, or is not relevant there.
```suggestion
PRs can target other branches (e.g. `3.2`, `3.5`) if the same change was done in `master`, or is not relevant there.
PRs must not target `stable`, as that branch is updated manually.
```

I'd still keep an example, and also mention that stable is not to be used.

2022-07-10 17:04 UTC, YuriSizov approved these changes

2022-07-10 18:44 UTC, merged

2022-07-10 18:44 UTC, YuriSizov commented
Thanks!