Singletons tutorial has deprecated methods.
godotengine/godot-docs pull request #6018
Opened 2022-08-01 19:56 UTC by Pixelatex

Replaced deprecated C# methods with their new versions in the singletons/autoload tutorial page.

2022-08-01 21:14 UTC, Calinou commented
Note that these methods are not deprecated (in the sense that they won't be removed in 4.0). Still, the property syntax is now preferred indeed.

2022-08-01 21:14 UTC, Calinou approved these changes
.

2022-08-01 21:14 UTC, Calinou requested changes
Before merging, could you apply the same changes to the GDScript code blocks?

2022-08-02 20:38 UTC, Pixelatex commented
@Calinou Unless I'm mistaken, GDscript doesn't have a new different syntax for these methods.

I assume they were changed for consistency with other methods in C# because they were using snake case before instead of PascalCase

2022-08-02 20:40 UTC, Calinou commented
> Unless I'm mistaken, GDscript doesn't have a new different syntax for these methods.

As of Godot 3.4 (and possibly before), there is a `root` property in SceneTree which can be used as an alternative to `get_root()`. The same likely applies to `current_scene`.

2022-08-02 20:49 UTC, Pixelatex commented
> > Unless I'm mistaken, GDscript doesn't have a new different syntax for these methods.
> 
> As of Godot 3.4 (and possibly before), there is a `root` property in SceneTree which can be used as an alternative to `get_root()`. The same likely applies to `current_scene`.

There's no reference to something other than get_root in the doscs and testing it in 3.4.4stable, get_tree().root or .Root is not valid. Are you sure?

2022-08-02 21:08 UTC, Pixelatex commented
p.s. @Calinou , unless I'm mistaken, these new methods are nowhere to be found in the docs, want me to add a PR for that as well?

2022-08-03 19:40 UTC, mhilbrunner commented
> p.s. @Calinou , unless I'm mistaken, these new methods are nowhere to be found in the docs, want me to add a PR for that as well?

They are documented I believe?

https://docs.godotengine.org/en/latest/classes/class_scenetree.html#class-scenetree-property-root

https://docs.godotengine.org/en/latest/classes/class_scenetree.html#class-scenetree-property-current-scene

2022-08-05 17:54 UTC, mhilbrunner approved these changes

2022-08-05 17:54 UTC, merged

2022-08-05 17:54 UTC, mhilbrunner commented
Thanks, and congrats on your first contribution to Godot's docs!

2022-08-06 02:54 UTC, Calinou commented
Cherry-picked to the `3.5`, `stable` and `3.4` branches.