removed use of "banned words" to comply with "Docs writing guidelines"
godotengine/godot-docs pull request #6091
Opened 2022-08-20 13:46 UTC by WakaJoekoe

[The writing guidelines](https://docs.godotengine.org/en/latest/community/contributing/docs_writing_guidelines.html#ban-these-8-words) specify a list of 8 banned words. I have edited some files so that they do not contain these banned words.

2022-08-20 15:29 UTC, Calinou requested changes
Looks good to me, but please remove the `class_packetpeer.rst` change as it will be lost when the class reference is updated.

Contributions to the class reference should be sent on the main Godot repository, not here. This is because the class reference in this repository is generated automatically based on the XML files in the main repository. See [Contribute to the class reference](https://docs.godotengine.org/en/latest/community/contributing/updating_the_class_reference.html) in the documentation :slightly_smiling_face:

2022-08-24 12:37 UTC, skyace65 requested changes
Looks good so far. Rebasing should fix the build issue. Also once you're done these commits need to be squashed.

2022-08-24 12:37 UTC, skyace65 commented on development/compiling/cross-compiling_for_ios_on_linux.rst
> +but once you have the environment properly configured, you can
```suggestion
but once you have the environment properly configured you can
```

2022-08-24 12:37 UTC, skyace65 commented on tutorials/export/exporting_pcks.rst
> +This tutorial should illustrate how to add mods, patches, or DLC to a game.
```suggestion
This tutorial explains how to add mods, patches, or DLC to a game.
```

2022-08-24 12:37 UTC, skyace65 commented on tutorials/plugins/editor/making_main_screen_plugins.rst
> +that extends the editor. Main screen plugins allow you to create
```suggestion
Main screen plugins allow you to create
```
I think for this the paragraph flows better if the sentence is removed entirely.

2022-08-24 17:26 UTC, mhilbrunner commented
Salvaged to fix CI in https://github.com/godotengine/godot-docs/pull/6102, giving credit to @WakaJoekoe and applying the last suggestions above.

🎉 Thanks for contributing, congrats on your first contribution, and sorry the CI was a bit messed up :) It's fixed now!

2022-08-24 17:26 UTC, closed without merging