update "Apply Reset" option location
godotengine/godot-docs pull request #6135
Opened 2022-09-04 17:18 UTC by bfedie518

Under USING RESET tracks, it said the "Apply Reset" option was in the "Animation" dropdown menu.  It's actually located in the "Edit" dropdown menu.

2022-09-04 17:46 UTC, Calinou commented
Is this only the case in 4.0.alpha, or also in 3.5?

2022-09-04 18:19 UTC, bfedie518 commented
This is the case in 3.5.

On Sun, Sep 4, 2022 at 12:46 PM Hugo Locurcio ***@***.***>
wrote:

> Is this only the case in 4.0.alpha, or also in 3.5?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/godotengine/godot-docs/pull/6135#issuecomment-1236386781>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AED26CAWY7PQNGE7TTSXRF3V4TOADANCNFSM6AAAAAAQEM7UCA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-09-19 02:40 UTC, skyace65 requested changes
I confirmed it is in the edit dropdown instead of animation. I just need you to squash the commits for this PR so it can be merged. If you don't know how to do that we have a guide [here](https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html#the-interactive-rebase).

2022-09-20 02:23 UTC, skyace65 approved these changes
Thanks!

2022-09-20 02:24 UTC, merged

2024-09-10 12:15 UTC, mhilbrunner commented
Cherry-picked to 3.6 in https://github.com/godotengine/godot-docs/pull/9936.