Updating change_scene and chnage_scene_to
godotengine/godot-docs pull request #6175
Opened 2022-09-14 00:15 UTC by Kirrby

solves #6156

2022-09-14 11:37 UTC, Jayman2000 requested changes
This PR introduces two warnings:

<pre><samp>/home/jayman/Documents/Home/VC/Partially mine/godot-docs/repo/tutorials/scripting/scene_tree.rst:142: WARNING: undefined label: class_scenetree_method_change_scene
/home/jayman/Documents/Home/VC/Partially mine/godot-docs/repo/tutorials/scripting/scene_tree.rst:160: WARNING: undefined label: class_scenetree_method_change_scene_to
</samp></pre>

If you fix those links, the warnings should go away.

2022-09-14 11:37 UTC, Jayman2000 commented on tutorials/scripting/scene_tree.rst
> +:ref:`SceneTree.change_scene_to_file() <class_SceneTree_method_change_scene>`
You also need to update the `<class_SceneTree_method_…>` part or else the link won’t work.

2022-09-14 11:37 UTC, Jayman2000 commented on tutorials/scripting/scene_tree.rst
> +:ref:`SceneTree.change_scene_to_packed(PackedScene scene) <class_SceneTree_method_change_scene_to>`:
Ditto.

2022-09-14 20:26 UTC, YuriSizov commented
You also have a typo in your commit message, which is worth fixing when you'll be rebasing this PR after applying the suggested changes and fixes.

2022-09-14 20:29 UTC, Kirrby commented
ah damn didnt see that, will fix

2022-09-14 20:52 UTC, Kirrby commented
ok sorry for not being the smartest (im very new to github and all that) i made the changes on my repo, how do i add them to this pr? i also made the changes directly on the browser editor so i think that doesnt help at all.

2022-09-14 21:04 UTC, YuriSizov commented
> ok sorry for not being the smartest (im very new to github and all that) i made the changes on my repo, how do i add them to this pr? i also made the changes directly on the browser editor so i think that doesnt help at all.

If you make changes to the same branch, they will just appear here. If you've made a new branch, then this won't work. You also can't rebase or squash using the GitHub's web UI and need to use a desktop client for Git to do that.

2022-09-14 21:06 UTC, Kirrby commented
ah, okay, imma make the changes on the right branch

2022-09-14 21:13 UTC, Kirrby commented
ok changes made

2022-09-14 21:13 UTC, Kirrby commented
i think that should be all but i'll check

2022-09-15 09:54 UTC, Jayman2000 commented
I found two more places that need to be updated:

```console
$ git grep -P 'change_scene(?!_to_(file|packed))'
[…]
tutorials/scripting/singletons_autoload.rst:        # Optionally, to make it compatible with the SceneTree.change_scene() API.
tutorials/scripting/singletons_autoload.rst:        // Optionally, to make it compatible with the SceneTree.change_scene() API.
```

2022-10-05 10:57 UTC, mhilbrunner approved these changes

2022-10-05 10:57 UTC, merged

2022-10-05 10:58 UTC, mhilbrunner commented
Thanks and congrats on your first merged PR to Godot Engine's documentation! And thanks for everyone helping to point out things :)

2022-10-05 21:21 UTC, Kirrby commented
> Thanks and congrats on your first merged PR to Godot Engine's documentation! And thanks for everyone helping to point out things :)

Thanks!