[2D Game Tutorial - Creating the Enemy] Minor clarification on 3 lines
godotengine/godot-docs pull request #6226
Opened 2022-09-27 12:03 UTC by TheYellowArchitect

2022-10-01 15:06 UTC, mhilbrunner commented on getting_started/first_2d_game/04.creating_the_enemy.rst
> +In the properties of :ref:`RigidDynamicBody2D <class_RigidDynamicBody2D>` (named ``Mob``), set ``Gravity Scale``
```suggestion
In the properties of the :ref:`RigidDynamicBody2D <class_RigidDynamicBody2D>` (named ``Mob``), set ``Gravity Scale``
```

2022-10-01 15:06 UTC, mhilbrunner commented on getting_started/first_2d_game/04.creating_the_enemy.rst
> +        queue_free() #Destroys this node in the next frame
```suggestion
        queue_free() # Destroys this node in the next frame
```

2022-10-01 15:06 UTC, mhilbrunner commented on getting_started/first_2d_game/04.creating_the_enemy.rst
> +Connect the ``screen_exited()`` signal of the ``VisibleOnScreenNotifier2D`` node onto the ``Mob`` and
```suggestion
Connect the ``screen_exited()`` signal of the ``VisibleOnScreenNotifier2D`` node to the ``Mob`` and
```

2022-10-01 15:07 UTC, mhilbrunner requested changes
Nice! Some minor changes to improve consistency with other docs above.

2022-10-01 23:03 UTC, TheYellowArchitect commented
I agree with all of them and made the changes, you have a good eye to catch those hahaha

2023-04-26 18:22 UTC, Vennnot commented
This can now be merged, no?

2023-05-18 11:14 UTC, mhilbrunner commented
I've salvaged a change from this in https://github.com/godotengine/godot-docs/pull/7372. For the others, I think they aren't necessary - three lines above the first it is pointed out very clearly that the `Mob` node is being referred to, and the `queue_free()` comment IMO isn't necessary.

Thanks for contributing!

2023-05-18 11:14 UTC, closed without merging

2023-05-18 16:45 UTC, TheYellowArchitect commented
I thank you :)