[Introduction to 3D] Spatial node replaced with Node3D
godotengine/godot-docs pull request #6244
Opened 2022-09-29 15:23 UTC by TheYellowArchitect

Spatial node does not exist in 4.0
This has been confirmed in https://github.com/godotengine/godot-docs/issues/6241 and fixes it.

There may be other instances of the Spatial node in the docs, but this is the main one and the easiest to stumble (literally first thing in 3D section lol)

2022-09-30 13:36 UTC, lucashilles approved these changes
LGTM

2022-09-30 17:36 UTC, Calinou commented on tutorials/3d/introduction_to_3d.rst
>  ~~~~~~~~~~~~
Title underline length must match the text (this is a reStructuredText requirement):

```suggestion
Node3D
~~~~~~
```

2022-09-30 17:37 UTC, Calinou requested changes
The `img/tuto_3d1.png` screenshot must be updated before this can be merged.

2022-10-01 22:54 UTC, TheYellowArchitect commented
I agree. Give me a few days as I suddenly got a small project I must rush to finish, then I will update this with a new image and the ~~~~~~~ suggestion :+1:

2022-10-04 04:57 UTC, TheYellowArchitect commented
https://docs.godotengine.org/en/latest/tutorials/3d/introduction_to_3d.html?highlight=spatial#spatial-node
It seems there are 2 more images in the above page using the Spatial node, so I updated them as well.

However, there is a problem with size. My new `tuto_3d2`:
`img/tuto_3d2.png` is 16KB
`img/tuto_3d2.webp` is 6KB

Its over 50% difference, but its just 16KB so no big deal.

However, `tuto_3d3` is a fullscreen image pretty much. The initial snapshot png is 329KB. Exporting it as .png via GIMP makes it 283KB. Via jpg in an acceptable quality, 91 KB. webp in slightly worse quality than jpg is 42KB. For context, existing/current `tuto_3d3.png` is 69KB. I uploaded the .webp, and want to strongly support implementation for .webp (if it doesn't exist already, cant build docs to confirm for myself)
Related to https://github.com/godotengine/godot-docs/issues/6173

Anyway, for `tuto_3d2` I used .png (just 16KB), and for `tuto_3d3` I used .jpg (91KB) instead of .webp (42KB), so there should be no problem merging this. But for when .webp is added, I have also included the `.webp` of the above images in the folder, so they can be used instead with just a simple line change in text, without uploading any image.

P.S. I use `maim` for taking images of editor, and then export them with GIMP

2023-04-26 18:20 UTC, Vennnot commented
This can be merged now, no?

2023-05-18 11:06 UTC, mhilbrunner commented
This has been fixed in https://github.com/godotengine/godot-docs/pull/6315.
If the images still need to be updated, a new PR is welcome for that :)

2023-05-18 11:06 UTC, closed without merging