Improve description of `range` function.
godotengine/godot-docs pull request #6280
Opened 2022-10-07 18:45 UTC by HolonProduction

Fixes #5763

The description from before did not take negative `s` into account.

2022-10-07 21:02 UTC, TheYellowArchitect commented on tutorials/scripting/gdscript/gdscript_advanced.rst
> +    range(b, n) # Will count from b to n in steps of 1. The parameters b and n are inclusive and exclusive, respectively.
For non-native english speakers, this is easier to understand (line 368)
`range(b, n) # Will count from b to n in steps of 1. The parameter b is inclusive. The parameter n is exclusive.`
Same applies for line 369

2022-10-07 21:03 UTC, TheYellowArchitect requested changes
For non-native english speakers, this is easier to understand (line 368)
`range(b, n) # Will count from b to n in steps of 1. The parameter b is inclusive. The parameter n is exclusive.`
Same applies for line 369

2022-10-07 23:10 UTC, TheYellowArchitect approved these changes

2022-10-07 23:11 UTC, TheYellowArchitect commented
Looks great, awaiting for merging :+1:

2022-10-11 06:06 UTC, merged

2022-10-11 06:06 UTC, mhilbrunner commented
Looks good, thank you and congrats on your first contribution to Godot's docs! 🎉