Add convention comparison chart to Introduction to 3D
godotengine/godot-docs pull request #6307
Opened 2022-10-13 21:53 UTC by Calinou

This is useful information when porting code or assets from another
3D engine. The chart was created by [Freya Homlér](https://mobile.twitter.com/FreyaHolmer).

See https://github.com/godotengine/godot-docs/issues/6272.

2022-10-14 02:15 UTC, skyace65 requested changes
1 minor issue but this looks good. Also I know we're debating moving to webp for images and one of the potential issues is making the repository bigger with format conversions. Since this is a brand new image should it be webp since it avoids that issue?

2022-10-14 02:15 UTC, skyace65 commented on tutorials/3d/introduction_to_3d.rst
> +See this chart for comparison with other 3D engines:
```suggestion
See this chart for comparison with other 3D software:
```

2022-10-14 11:53 UTC, mhilbrunner commented
> we're debating moving to webp
We should come to a decision on this, but I think moving to .webp for _new_ images makes sense at this point.

2022-10-17 09:27 UTC, fire commented
Did we have a note of permission for Freya's image?

2022-10-17 12:15 UTC, Calinou commented
> Did we have a note of permission for Freya's image?

No, but feel free to ask her if you find a way to.

2022-10-18 02:51 UTC, mhilbrunner commented
> > Did we have a note of permission for Freya's image?
> 
> No, but feel free to ask them if you find a way to.

Reached out to ask for permission, which we definitely should get before/if we add this. It's a great graphic though.

2022-10-18 10:40 UTC, mhilbrunner commented
Freya gave the OK on using it and licensing it as CC BY, as long as its with attribution and a link to https://twitter.com/FreyaHolmer

2022-10-18 21:06 UTC, Calinou commented
> Freya gave the OK on using it and licensing it as CC BY, as long as its with attribution with name + a link to [twitter.com/FreyaHolmer](https://twitter.com/FreyaHolmer)

Done.

2022-10-18 21:15 UTC, fire approved these changes

2022-10-21 02:51 UTC, skyace65 approved these changes

2022-10-21 15:19 UTC, merged

2022-10-21 16:04 UTC, mhilbrunner commented
Pushed the .webp update. Thanks for the PR & merge :)