Add a page on custom performance monitors
godotengine/godot-docs pull request #6409
Opened 2022-11-21 23:04 UTC by Calinou

There's probably a bit more information that could be added, but I'm not too sure what to add right now.

2022-11-23 20:53 UTC, mhilbrunner approved these changes

2022-12-12 03:50 UTC, skyace65 requested changes
Looks very good! I only have 1 issue.

2022-12-12 03:50 UTC, skyace65 commented on tutorials/scripting/debug/custom_performance_monitors.rst
> +The second parameter is a :ref:`class_Callable`.
This sentence seems out of place. I assume it's referring to `Performance.add_custom_monitor()`, but it's several paragraphs after that part of the code, I thought it was referring to something related to what you see in the debugger panel at first.

2022-12-12 13:36 UTC, skyace65 approved these changes

2022-12-19 16:48 UTC, merged