Update GDScript Export Docs
godotengine/godot-docs pull request #6481
Opened 2022-12-11 21:30 UTC by Piralein

- Update and sort the annotation table in gdscript_basics.
- add section "grouping" in gdscript_export.
- rearrange "enums" to its own section outside of basic usage and add better hints.
- remove some unneeded code and add a link to the gdscript annotation page in classref.

2022-12-28 13:50 UTC, YuriSizov commented
> Update and sort the annotation table in gdscript_basics.

As discussed in https://github.com/godotengine/godot-docs/pull/6491, this table should probably be removed and we should link to the `@GDScript` article in the class reference, where all annotations are already explained with proper examples. The GDScript exports article should be linked there as well, if not already.

You can give it a go, updating your PR, or I can fix it in a separate one.

2022-12-28 13:53 UTC, YuriSizov commented on tutorials/scripting/gdscript/gdscript_exports.rst
> +For more information about export annotations see :ref:`GDScript annotations <class_@GDScript>`.
I agree that the original sentence is no longer valid, but that's a weird thing to say in an article that exists to provide more information about export annotations itself :)

2022-12-28 13:56 UTC, YuriSizov commented on tutorials/scripting/gdscript/gdscript_exports.rst
>  In that example the value `5` will be saved and visible in the property editor.
This probably needs two ticks on each side, I think it should be formatted as code.

2022-12-28 14:23 UTC, YuriSizov requested changes
A few more review notes

2022-12-28 14:23 UTC, YuriSizov commented on tutorials/scripting/gdscript/gdscript_exports.rst
> +Groups cannot be nested, use :ref:`@export_subgroup <class_@GDScript_annotation_@export_subgroup>` to add subgroups within groups.
These lines should be wrapped to keep the style of the document consistent. We don't do it everywhere, but in this particular article we do, so the formatting style should be preserved.

```suggestion
It is possible to group your exported properties inside the Inspector
with the :ref:`@export_group <class_@GDScript_annotation_@export_group>`
annotation. Every exported property after this annotation will be added to
the group. Start a new group or use ``@export_group("")`` to break out.

::

    @export_group("My Properties")
    @export var number = 3
    @export var string = ""

Second argument of the annotation can be used to only group properties
with the specified prefix.

Groups cannot be nested, use :ref:`@export_subgroup <class_@GDScript_annotation_@export_subgroup>`
to create subgroups within a group.
```

2022-12-28 14:23 UTC, YuriSizov commented on tutorials/scripting/gdscript/gdscript_exports.rst
> +    @export var string = ""
```suggestion
    @export_group("My Properties")
    @export var number = 3
    
    @export_subgroup("Extra Properties")
    @export var string = ""
    @export var flag = false
```

2022-12-28 14:23 UTC, YuriSizov commented on tutorials/scripting/gdscript/gdscript_exports.rst
> +You can also change the name of the category with the :ref:`@export_category <class_@GDScript_annotation_@export_category>` annotation.
```suggestion
You can also change the name of your main category, or create additional
categories in the property list with the :ref:`@export_category <class_@GDScript_annotation_@export_category>`
annotation.

.. note::

    The list of properties is organized based on the class inheritance and
    new categories break that expectation. Use them carefully, especially
    when creating projects for public use.
```

2022-12-28 14:23 UTC, YuriSizov commented on tutorials/scripting/gdscript/gdscript_exports.rst
> +    @export_category("My Category")
```suggestion
    @export_category("Main Category")
    @export var number = 3
    @export var string = ""
    
    @export_category("Extra Category")
    @export var flag = false
```

2022-12-28 14:23 UTC, YuriSizov commented on tutorials/scripting/gdscript/gdscript_exports.rst
> +The Editor will enumerate as ``0`` THING_1, ``1`` THING_2, ``-1`` ANOTHER_THING.
```suggestion
Properties can be exported with a type hint referencing an enum to limit their values
to the values of the enumeration. The editor will create a widget in the Inspector, enumerating
the following as THING_1, THING_2, ANOTHER_THING. The value will be stored as an integer.
```

2022-12-28 14:23 UTC, YuriSizov commented on tutorials/scripting/gdscript/gdscript_exports.rst
> +The Editor will enumerate as ``0`` Warrior, ``1`` Magician, ``2`` Thief.
```suggestion
Integer and string properties can also be limited to a specific list of values using
the :ref:`@export_enum <class_@GDScript_annotation_@export_enum>` annotation.
The editor will create a widget in the Inspector, enumerating the following as Warrior,
Magician, Thief. The value will be stored as an integer, corresponding to the index
of the selected option (i.e. ``0``, ``1``,  or ``2``).
```

2022-12-28 14:23 UTC, YuriSizov commented on tutorials/scripting/gdscript/gdscript_exports.rst
> +If the type is a String, the editor will enumerate with string names.
```suggestion
If the type is String, the value will be stored as a string.
```

2022-12-28 17:17 UTC, Piralein commented
I removed the table and linked to the class ref/ gdscript export page.

2022-12-28 18:48 UTC, YuriSizov approved these changes
> I also moved the onready block directly beneath it.

Yeah, good call!

Looks good now, apart from a couple of formatting corrections.

2022-12-28 18:48 UTC, YuriSizov commented on tutorials/scripting/gdscript/gdscript_basics.rst
> +For more information about exporting variables, read the :ref:`GDScript export article <doc_gdscript_exports>`.
```suggestion
For more information about exporting properties, read the :ref:`GDScript exports <doc_gdscript_exports>`
article.
```

2022-12-28 18:48 UTC, YuriSizov commented on tutorials/scripting/gdscript/gdscript_exports.rst
> +    The list of properties is organized based on the class inheritance and
A new line is required here.

```suggestion
.. note::

    The list of properties is organized based on the class inheritance and
```

2022-12-29 23:18 UTC, merged

2022-12-29 23:18 UTC, YuriSizov commented
Thanks!