Fix Navigation doc for different actor types due to recent renames
godotengine/godot-docs pull request #6507
Opened 2022-12-22 22:41 UTC by smix8

Fixes Navigation doc for different actor types due to recent renames.

2022-12-23 15:35 UTC, mhilbrunner approved these changes

2022-12-24 14:49 UTC, skyace65 requested changes

2022-12-24 14:49 UTC, skyace65 commented on tutorials/navigation/navigation_different_actor_types.rst
> +   Agents are exclusively defined by a radius and height value for baking navigation mesh, pathfinding and avoidance. More complex shapes are not supported.
```suggestion
   Agents are exclusively defined by a radius and height value for baking navigation meshes, pathfinding and avoidance. More complex shapes are not supported.
```

2022-12-26 16:22 UTC, skyace65 approved these changes

2022-12-27 16:53 UTC, merged

2022-12-27 16:53 UTC, mhilbrunner commented
Thanks! 🎉 ❄️