Update c# code example and remove randomize call (your first 2d game - the main game scene)
godotengine/godot-docs pull request #6580
Opened 2023-01-11 18:45 UTC by Piralein

closes #6549 

Added ``using`` directive and ``partial`` keyword
Removed the randomize() call at startup, according to [comment](https://github.com/godotengine/godot-docs/pull/6008#issuecomment-1279210051).
(please check c++ carefully, I'm not familiar with it)

2023-01-11 20:44 UTC, mhilbrunner commented
Thanks for contributing! cc @raulsntos

2023-01-11 22:18 UTC, raulsntos requested changes

2023-01-11 22:18 UTC, raulsntos commented on getting_started/first_2d_game/05.the_main_game_scene.rst
> -        godot::Ref<godot::RandomNumberGenerator> _random;
The field can't be removed, it's used later to generate random numbers.

2023-01-11 22:18 UTC, raulsntos commented on getting_started/first_2d_game/05.the_main_game_scene.rst
> -        _random->randomize();
The `_random` field initialization shouldn't be removed, the `randomize()` method is fine to remove.

2023-01-13 02:24 UTC, raulsntos approved these changes

2023-01-13 13:31 UTC, merged

2023-01-13 13:31 UTC, YuriSizov commented
Thanks!