Fixed a small typo on Pause Mode documentation
godotengine/godot-docs pull request #6624
Opened 2023-01-17 07:29 UTC by pgpais

In the Pause Mode documentation, in the Pause Menu example, it was still referring to the old "Process" pause mode. I changed it to refer to "When Paused" and "Always" (as both seemed correct to me)

2023-01-18 00:45 UTC, skyace65 requested changes
Good catch! However I think that part should just use "when paused" for the example, as there's not really a use case for a pause menu processing when the game is running.

2023-01-18 00:45 UTC, skyace65 commented on tutorials/scripting/pausing_games.rst
> +root of the pause popup to "When Paused" or "Always", all children and grandchildren will
```suggestion
inside, and set its pause mode to "When Paused" then hide it. By setting the
root of the pause popup to "When Paused", all children and grandchildren will
```

2023-01-18 07:28 UTC, pgpais commented
Right. I wasn't sure if _Show()_ would happen if the node isn't being processed, hence my suggestion.

2023-01-19 00:56 UTC, skyace65 commented
It will work as long as the script isn't attached to something with the process mode "when paused", I just confirmed this with the latest beta.

2023-01-19 00:56 UTC, skyace65 approved these changes
Thanks! And congrats on your first merged PR.

2023-01-19 00:58 UTC, merged