Update majority of images in "Your first 2d game"
godotengine/godot-docs pull request #6697
Opened 2023-01-29 16:58 UTC by Piralein

Update majority of images to new layout and change some of the text referring to images.

Not included:
- new-project-button.png
- folder-content.png
- player_coll_shape.png
- mob_animations.gif

TODO:
everything after "creating the enemy"

2023-01-29 20:21 UTC, skyace65 requested changes
Needs a little work but overall this is a fantastic PR! The image quality is perfect and exactly in line with the new guidelines.

2023-01-29 20:21 UTC, skyace65 commented on getting_started/first_2d_game/03.coding_the_player.rst
> +.. image:: img/input-mapping-event-configuration.webp
```suggestion
The "Listening for Input..." field should automatically be selected. Press the "right" key on your keyboard, and the menu should look like this now.

.. image:: img/input-mapping-event-configuration.webp

Select the "ok" button. The "right" key is now associated with the ``move_right`` action.
```

2023-01-29 21:39 UTC, Piralein commented on getting_started/first_2d_game/02.player_scene.rst
> +.. image:: img/add_node.webp
Yes, I forgot to turn on 3d, fixed.^^"

2023-01-29 21:42 UTC, Piralein commented
I renamed the font pictures to something more descriptive.
I also removed the `Player` part of the signal connection, it is not part of the autogenerated name.
(please check the cpp part carefully, I'm still not really familiar with it)

2023-01-29 23:02 UTC, skyace65 approved these changes
All good now! Thanks a ton for this! Just for future reference we like to keep everything in a PR as one commit. I'm going to squash and merge this now but keep it in mind for future reference. If you don't know how to do it we have a guide on [this page](https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html).

2023-01-29 23:03 UTC, merged

2023-01-30 08:19 UTC, Piralein commented
I wanted to keep it separate for easier review and squash after approval.
Didin't expect it to be this fast. 😄