Use new API for 4.0
godotengine/godot-docs pull request #6699
Opened 2023-01-30 04:39 UTC by shanempope

2023-02-03 01:56 UTC, skyace65 requested changes
Looks good! Would you mind also updating the GDScript code?

2023-02-03 19:27 UTC, shanempope commented
Don't have a GDScript project to test in. Just checked the [docs](https://docs.godotengine.org/en/latest/classes/class_animatedsprite2d.html#class-animatedsprite2d-property-sprite-frames) and updated it the same

2023-02-04 00:26 UTC, skyace65 approved these changes

2023-02-04 00:28 UTC, skyace65 commented
Thanks! and congrats on your first merged PR! For future reference try to keep everything in 1 commit, I can do a squash merge for this but keep that in mind for next time. If you don't know how to do that we go over it on [this page](https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html).

2023-02-04 00:28 UTC, merged