small c# fix in the "Arc polygon function" section
godotengine/godot-docs pull request #6729
Opened 2023-02-03 18:12 UTC by Crystelmarv

i needs to start at 1 so "pointsArc[0] = center;" is not overridden

2023-02-03 19:30 UTC, raulsntos requested changes

2023-02-03 19:30 UTC, raulsntos commented on tutorials/2d/custom_drawing_in_2d.rst
>              pointsArc[i] = center + new Vector2(Mathf.Cos(anglePoint), Mathf.Sin(anglePoint)) * radius;
This misses the `anglePoint` for i = 0. I think the equivalent of the GDScript version would be something like this:

```suggestion
        for (int i = 0; i <= nbPoints; i++)
        {
            float anglePoint = Mathf.Deg2Rad(angleFrom + i * (angleTo - angleFrom) / nbPoints - 90);
            pointsArc[i + 1] = center + new Vector2(Mathf.Cos(anglePoint), Mathf.Sin(anglePoint)) * radius;
```

2023-02-03 22:37 UTC, raulsntos commented on tutorials/2d/custom_drawing_in_2d.rst
> +            pointsArc[i+1] = center + new Vector2(Mathf.Cos(anglePoint), Mathf.Sin(anglePoint)) * radius;
```suggestion
            pointsArc[i + 1] = center + new Vector2(Mathf.Cos(anglePoint), Mathf.Sin(anglePoint)) * radius;
```

2023-02-03 22:37 UTC, raulsntos approved these changes

2023-02-04 16:27 UTC, merged

2023-02-04 16:27 UTC, YuriSizov commented
Thanks, and congrats on the first merged docs PR!