Update TileSets and TileMaps documentation for Godot 4.0
godotengine/godot-docs pull request #6760
Opened 2023-02-10 16:30 UTC by Calinou

The documentation was split into two pages, as there are much more features to cover now.

There are still features to document, but this should be a good start to review and proofread already. I've tried to keep the documentation concise but also detailed enough to cover complex use cases, while also being accessible to beginners.

## TODO

- Document terrains.
- Document tile proxies.
- Document scene tile import.

2023-02-10 22:34 UTC, skyace65 commented on tutorials/2d/using_tilemaps.rst
> +If you right-click while in redctangle paint mode, erasing will be performed in
```suggestion
If you right-click while in rectangle paint mode, erasing will be performed in
```

2023-02-10 22:43 UTC, skyace65 requested changes
Didn't get to do a read through, just checked it for spelling and grammar errors. These two were the only I found.

2023-02-10 22:43 UTC, skyace65 commented on tutorials/2d/using_tilesets.rst
> +- **Alternative ID:** The unique numerical identifier for this alterantive tile.
```suggestion
- **Alternative ID:** The unique numerical identifier for this alternative tile.
```

2023-02-13 19:41 UTC, letmetrythisname commented
Revised both documents.
[isaac-edits-diff.txt](https://github.com/godotengine/godot-docs/files/10725715/isaac-edits-diff.txt)

2023-02-15 19:26 UTC, Calinou commented
> Great work overall. Just made a few revisions to both documents: mainly corrected uses of passive voice and truncated/split longer sentences to make them easier to read. [isaac-edits-diff.txt](https://github.com/godotengine/godot-docs/files/10725715/isaac-edits-diff.txt)


Thanks! I've applied those changes and added you as a co-author :slightly_smiling_face:

2023-02-27 02:39 UTC, mhilbrunner approved these changes

2023-02-27 05:12 UTC, mhilbrunner commented
Pushed to make CI happy (adding a newline at the end of the index file, fixing a `readadd` -> `re-add` typo and erroneous space at a beginning of a line in `using_tilemapst.rst`).

Great work, thanks!

2023-02-27 05:13 UTC, merged