Add documentation about XR room scale
godotengine/godot-docs pull request #6774
Opened 2023-02-13 13:22 UTC by BastiaanOlij

This documentation page makes an attempt at explaining an issue that almost all developers trying XR for the first time, how to properly deal with movement when room scale tracking is used.

Still todo:
- Add animation/screenshots
- Test code for origin based setup
- Add code for character based setup
- Add info about dealing with a player physically moving to an impossible location.

2023-02-17 22:51 UTC, skyace65 requested changes

2023-02-17 22:51 UTC, skyace65 commented on tutorials/xr/xr_room_scale.rst
> +This will cause nausia for the player.
```suggestion
This will cause nausea for the player.
```

2023-02-17 22:51 UTC, skyace65 commented on tutorials/xr/xr_room_scale.rst
> +This function should implement obtaining the necesairy input and return the rotational speed in radians per second.
```suggestion
This function should implement obtaining the necessary input and return the rotational speed in radians per second.
```

2023-02-17 22:51 UTC, skyace65 commented on tutorials/xr/xr_room_scale.rst
> +This will ensure that the players location stays in sync with the character bodys location.
```suggestion
This will ensure that the players location stays in sync with the character body's location.
```

2023-02-17 22:51 UTC, skyace65 commented on tutorials/xr/xr_room_scale.rst
> +This function should implement obtaining the necesairy input and return a directional vector scaled to the required velocity.
```suggestion
This function should implement obtaining the necessary input and return a directional vector scaled to the required velocity.
```

2023-02-17 22:51 UTC, skyace65 commented on tutorials/xr/xr_room_scale.rst
> +This function should implement obtaining the necesairy input and return the rotational speed in radians per second.
```suggestion
This function should implement obtaining the necessary input and return the rotational speed in radians per second.
```

2023-02-17 22:51 UTC, skyace65 commented on tutorials/xr/xr_room_scale.rst
> +This function should implement obtaining the necesairy input and return a directional vector scaled to the required velocity.
```suggestion
This function should implement obtaining the necessary input and return a directional vector scaled to the required velocity.
```

2023-02-17 22:51 UTC, skyace65 commented on tutorials/xr/xr_room_scale.rst
> +This space is often constraint by the room the player is physically in with tracking sensors placed within this space.
```suggestion
This space is often constrained by the room the player is physically in with tracking sensors placed within this space.
```

2023-02-17 22:51 UTC, skyace65 commented on tutorials/xr/xr_room_scale.rst
> +  The advise here is to start testing while standing up and walking around as early as possible.
```suggestion
  The advice here is to start testing while standing up and walking around as early as possible.
```

2023-02-17 22:51 UTC, skyace65 commented on tutorials/xr/xr_room_scale.rst
> +However, at closer examination this model does not take into account that there are two forms of movement in XR.
```suggestion
However, upon closer examination this model does not take into account that there are two forms of movement in XR.
```

2023-02-18 11:04 UTC, BastiaanOlij commented
Ok, as far as I can test the sample code works as advertised so I'm happy

2023-02-18 12:41 UTC, skyace65 approved these changes

2023-02-18 17:14 UTC, mhilbrunner reviewed
Looks good to me. Very interesting read of the initial problems with VR/XR movement, as someone not that knowledgeable about that platform space :) Good read!

Left a few small nitpicks/typos/simplification suggestions.

2023-02-18 17:14 UTC, mhilbrunner commented on tutorials/xr/xr_room_scale.rst
> +A camera is attached to this node at a location roughly where the players head will be.
```suggestion
A camera is attached to this node at a location roughly where the player's head will be.
```

2023-02-18 17:14 UTC, mhilbrunner commented on tutorials/xr/xr_room_scale.rst
> +If we rotate our character body the player will be moved around the room in a circular fashion.
```suggestion
If we rotate our character body, the player will be moved around the room in a circular fashion.
```

2023-02-18 17:14 UTC, mhilbrunner commented on tutorials/xr/xr_room_scale.rst
> +Processing our character movement is now done in 3 steps.
```suggestion
Processing our character movement is now done in three steps.
```

2023-02-18 17:14 UTC, mhilbrunner commented on tutorials/xr/xr_room_scale.rst
> +Note that we're returning true from our ``_process_on_physical_movement`` function when we couldn't move our player all the way.
```suggestion
Note that we're returning ``true`` from our ``_process_on_physical_movement`` function when we couldn't move our player all the way.
```

2023-02-18 17:14 UTC, mhilbrunner commented on tutorials/xr/xr_room_scale.rst
> +This function should implement obtaining the necessary input and return the rotational speed in radians per second.
```suggestion
This function should obtain the necessary input and return the rotational speed in radians per second.
```

2023-02-18 17:14 UTC, mhilbrunner commented on tutorials/xr/xr_room_scale.rst
> +  We've added the call to processing our rotation to our physics process but we are only executing this if we were able to move our player fully.
```suggestion
  We've added the call for processing our rotation to our physics process but we are only executing this if we were able to move our player fully.
```

2023-02-18 17:14 UTC, mhilbrunner commented on tutorials/xr/xr_room_scale.rst
> +This function should implement obtaining the necessary input and return a directional vector scaled to the required velocity.
```suggestion
This function should obtain the necessary input and return a directional vector scaled to the required velocity.
```

2023-02-18 17:14 UTC, mhilbrunner commented on tutorials/xr/xr_room_scale.rst
> +Processing our character movement is done in the same 3 steps but implemented slightly differently.
```suggestion
Processing our character movement is done in the same three steps but implemented slightly differently.
```

2023-02-18 17:14 UTC, mhilbrunner commented on tutorials/xr/xr_room_scale.rst
> +This function should implement obtaining the necessary input and return a directional vector scaled to the required velocity.
```suggestion
This function should obtain the necessary input and return a directional vector scaled to the required velocity.
```

2023-02-23 07:47 UTC, merged

2023-02-23 07:47 UTC, akien-mga commented
Thanks!