In XR application V-sync should never be used
godotengine/godot-docs pull request #6883
Opened 2023-03-04 02:37 UTC by BastiaanOlij

XR applications are the one exception where we should never use v-sync. This adds a line of code to the example that forces v-sync off and adds an explanation to why this is needed.

2023-03-04 02:37 UTC, BastiaanOlij commented
Also fixed that the document was using tabs instead of spaces.

2023-03-04 07:59 UTC, Calinou requested changes
Text looks good to me, but 4 spaces should be used for indentation, not 2.

2023-03-06 02:49 UTC, BastiaanOlij commented
> Text looks good to me, but 4 spaces should be used for indentation, not 2.

Changed that :)

2023-03-09 04:07 UTC, mhilbrunner approved these changes

2023-03-09 04:08 UTC, merged

2023-03-09 04:08 UTC, mhilbrunner commented
In this goes! Thanks.