Update signals.rst to correct signal names.
godotengine/godot-docs pull request #7092
Opened 2023-03-30 09:26 UTC by MisoMosiSpy

Fixes https://github.com/godotengine/godot-docs/issues/7048

1. Update signal names as per the coding conventions
2. Update images to reflect correct signal names (Also changed them from png to webp)
3. Added note about signal callback names

2023-03-30 09:41 UTC, Piralein commented
There is already a PR for this: #7024 
(just for reference)

2023-03-30 09:45 UTC, Piralein requested changes

2023-03-30 09:45 UTC, Piralein commented on getting_started/step_by_step/signals.rst
> +:article_outdated: False
this line should be deleted and not set to false, as far as I know.

2023-03-30 09:45 UTC, Piralein commented on getting_started/step_by_step/signals.rst
> +          "_on_node_name_signal_name" and in C# as "OnNodeNameSignaName".
```suggestion
          "_on_node_name_signal_name" and in C# as "OnNodeNameSignalName".
```

2023-03-30 10:31 UTC, MisoMosiSpy commented on getting_started/step_by_step/signals.rst
> +          "_on_node_name_signal_name" and in C# as "OnNodeNameSignaName".
Thanks, updated as requested.

2023-03-30 10:33 UTC, MisoMosiSpy commented
> There is already a PR for this: #7024 (just for reference)

Oops, my bad I should have checked. Anyways I have updated this PR to address all comments, let the maintainers pick any PR for merging.

Thanks for the review.

2023-04-09 12:30 UTC, skyace65 approved these changes

2023-04-09 12:31 UTC, skyace65 commented
Merging this PR since the other one has not been updated.

2023-04-09 12:31 UTC, merged

2023-05-29 18:20 UTC, Glukozavr commented
Great guys! Sorry I got distracted with my pull-request, but glad it worked out anyway.