Tweak Vector math page (style, links, more notes)
godotengine/godot-docs pull request #7486
Opened 2023-06-08 14:22 UTC by akien-mga

Also cleanup style issues in the docs image guidelines.

2023-06-08 19:09 UTC, Piralein requested changes

2023-06-08 19:09 UTC, Piralein commented on contributing/documentation/docs_image_guidelines.rst
> +Where ``documentation_image.webp`` would be change to the name of the image you
```suggestion
Where ``documentation_image.webp`` would be changed to the name of the image you
```

2023-06-11 01:40 UTC, mhilbrunner commented on tutorials/math/vector_math.rst
> +    # information about the collision.
I wonder if its worth it to move this comment to the descriptive text, both to be able to link KinematicCollision2D and for the sake of translations. Also I agree this is an improvement over the original, but it starts to get a bit wordy for a comment compared to the length of the code.

Same for the C# version obviously. :)

2023-06-12 12:51 UTC, akien-mga commented on contributing/documentation/docs_image_guidelines.rst
> +Where ``documentation_image.webp`` would be change to the name of the image you
Fixed.

2023-06-13 10:47 UTC, Piralein approved these changes

2023-06-14 07:35 UTC, merged