Fixed Issue 'Broken link on internal_rendering_architecture page - 404 #7570'
godotengine/godot-docs pull request #7589
Opened 2023-07-01 15:02 UTC by KRybczynski

changed broken links from "Core GLSL material shaders" section of internal_rendering_architecture.rst to the ones provided in the issue description.

2023-07-05 12:53 UTC, clayjohn approved these changes

2023-07-05 22:28 UTC, skyace65 requested changes

2023-07-05 22:28 UTC, skyace65 commented on contributing/development/core_and_modules/internal_rendering_architecture.rst
> +- Forward Mobile: `servers/rendering/renderer_rd/shaders/scene_forward_mobile.glsl <https://github.com/godotengine/godot/blob/4.0/servers/rendering/renderer_rd/shaders/forward_mobile/scene_forward_mo
```suggestion
- Forward+: `servers/rendering/renderer_rd/shaders/forward_clustered/scene_forward_clustered.glsl <https://github.com/godotengine/godot/blob/4.0/servers/rendering/renderer_rd/shaders/forward_clustered/scene_forward_clustered.glsl>`__
- Forward Mobile: `servers/rendering/renderer_rd/shaders/forward_mobile/scene_forward_mobile.glsl <https://github.com/godotengine/godot/blob/4.0/servers/rendering/renderer_rd/shaders/forward_mobile/scene_forward_mobile.glsl>`__
```

2023-07-22 20:08 UTC, mhilbrunner approved these changes

2023-07-22 20:13 UTC, merged

2023-07-22 20:13 UTC, mhilbrunner commented
Thanks and congrats on your first merged contribution to Godot's docs!