Custom editor icon section's command wrong or out of data.
godotengine/godot-docs pull request #7820
Opened 2023-08-19 12:47 UTC by gogojokid

4.1.1.stable

https://docs.godotengine.org/en/latest/community/contributing/content_guidelines.html

In the "*.gdextension" code block, the [Icon] tag does not work in 4.1.1.stable version, and it does not match the naming conventions of other tags. I test it, [icons] tag is worked well. In addition, I added a blank lines between the tag and the content to make it more consistent with other "*.gdextension" code block formatting.

2023-09-01 15:14 UTC, capnm requested changes
Maybe change the name of the icon, it's not obvious that it doesn't have to be the same, e.g. "res://icon_gdexample.svg".

2023-09-01 17:07 UTC, paddy-exe approved these changes
Looks good. Had a look at Yuri's implementation PR details and `[icons]` is correct. Thanks for the correction!

2023-09-01 17:18 UTC, capnm commented
> The standard recommended procedure is to have icons stored in such a directory, see all the modules in the engine

These icons should be somewhere in the external extension directory? It isn't a internal module or part of the project.
res://??/icons/gd_example.svg ?

(It took me about an hour to figure out why it didn't work ;)

2023-09-01 20:58 UTC, AThousandShips commented
Can you please update your commit message, it says "out of data"

2023-09-02 10:51 UTC, YuriSizov commented
Commit message looks correct to me 👀

2023-09-02 10:57 UTC, AThousandShips commented
"Custom editor icon section's command wrong or out of data." not "date"

2023-09-02 11:02 UTC, YuriSizov commented
Ah, I thought you were seeing "out of data" as the entire commit message for some reason. My bad.

2023-09-02 14:53 UTC, AThousandShips commented
The message still says "out of data"

2023-09-02 15:02 UTC, gogojokid commented
> The message still says "out of data"

I am sorry, I spent some time looking at Godot's PR process and didn't notice it, it will change soon.

2023-09-02 15:08 UTC, capnm approved these changes

2023-09-03 13:21 UTC, capnm commented
Update2: I suggest leaving a comment there (correct me, but this doesn't seem to be documented anywhere) and using a relative path:
```
[icons]

; No res: and leading slash means it is relative to this gdextension file.
GDExample = "icons/gd_example.svg"
```

2023-09-03 14:00 UTC, AThousandShips commented
I think this is outside the scope of this PR, which is fixing a simple out of date description, needs to be discussed and looked into

2023-09-03 16:24 UTC, capnm commented
I'm now 'out of data' :smile: and hope that  someone someday hits the commit button.

2023-09-03 23:25 UTC, gogojokid commented
I think we should use "res://" here to reduce confusion, because on this page and elsewhere in the documentation, "res://" is always explicitly used for relative paths. Since it is a relative path, it means that the user can specify it freely, and technically can also use the path on the upper layer of the addon without any restrictions. For example, if you only make GDExtensions for your own use, these extensions can all read icons from the recommended global path "res://icons" for sharing. But if publishing them, it would be better to encapsulate the icons in the "res://addon/your_extension" directory.

To make this clearer, some more explanation could be added, and an example added, or stated in the Plugins section, since there seems to be no other mention of addons in this section. However, this PR is indeed just a simple fixing (sorry I didn’t use “Fixes” to start the title because I was not familiar with the PR process before). I agree with AtousandShips, we can merge it as soon as possible so that new users will no longer get the wrong information. Perhaps capnm can submit an Issue or PR as a discussion of Documentation Enhancement?

2023-09-10 20:25 UTC, dsnopek approved these changes

2023-09-11 14:22 UTC, mhilbrunner approved these changes

2023-09-11 14:23 UTC, merged

2023-09-11 14:24 UTC, mhilbrunner commented
Merges. Thanks and congrats on your first merged contribution to Godot's docs!

2023-10-08 23:11 UTC, mhilbrunner commented
Cherry-picked to 4.1