Fix description of GUI input propagation
godotengine/godot-docs pull request #7899
Opened 2023-09-09 21:18 UTC by wlsnmrk

As suggested in the contributors' chat, I'm submitting two competing fixes to godotengine/godot#81186, which reports a conflict between code behavior and documentation. This PR fixes documentation to match existing behavior. **_If maintainers prefer to change the behavior instead_**, I've opened a PR for that at [link to code PR will go here].

`Control::_gui_input()` calls only propagate up the scene tree for mouse events (when appropriate filter flags are set). Keyboard and controller events do not propagate through `_gui_input()`.

Additionally, current documentation splits the description of GUI input propagation around the description of Subviewport input handling.

This PR:
* Moves the separated parts of the GUI event description together in one location
* Marks it as a note to distinguish it from surrounding description of other input propagation
* Describes the different propagation behavior for keyboard and controller events, as compared to mouse events

2023-10-06 11:40 UTC, mhilbrunner commented
cc @Sauermann

2024-01-20 12:14 UTC, Sauermann approved these changes
The changes of this documentation update describe the current behavior better. So I would prefer this PR to https://github.com/godotengine/godot/pull/81499.

This PR will require an update because of a merge conflict.

2025-01-25 16:44 UTC, skyace65 approved these changes
Fixed the merge conflict and reviewed this. Can't speak to technical correctness but spelling and grammar wise everything looks good.

2025-01-25 16:48 UTC, skyace65 requested changes

2025-01-25 16:48 UTC, skyace65 commented on tutorials/inputs/inputevent.rst
> +   propagated as non-GUI events through :ref:`Node._unhandled_input() <class_Node_method__unhandled_input>`.
```suggestion
   propagated as non-GUI events through :ref:`Node._unhandled_input() <class_Node_private_method__unhandled_input>`.
```

2025-01-25 16:48 UTC, skyace65 approved these changes

2025-01-25 16:51 UTC, skyace65 commented
Fixed the class reference link

2025-01-25 16:51 UTC, merged