Added missing C# example in tutorials -> best practices -> godot_notifications.
godotengine/godot-docs pull request #7936
Opened 2023-09-16 20:31 UTC by GamEsnitzhel

There's a missing C# code example in https://docs.godotengine.org/en/latest/tutorials/best_practices/godot_notifications.html. All this does is add it in.

2023-09-17 00:11 UTC, raulsntos requested changes

2023-09-17 06:19 UTC, GamEsnitzhel commented on tutorials/best_practices/godot_notifications.rst
> +        public void _Process(double delta)
Yep! Thanks, I didn't catch that somehow.

2023-09-17 06:26 UTC, GamEsnitzhel commented on tutorials/best_practices/godot_notifications.rst
> +        public void _Process(double delta)
Changed it to `public void _Ready()`

2023-09-17 11:21 UTC, raulsntos commented on tutorials/best_practices/godot_notifications.rst
> +        public void _Ready()
The `_Ready` method is virtual, in C# you need to use the `override` keyword when overriding methods.

```suggestion
        public override void _Ready()
```

2023-09-17 18:42 UTC, raulsntos approved these changes
LGTM. Thanks!

2023-09-18 05:48 UTC, mhilbrunner approved these changes

2023-09-18 05:48 UTC, merged

2023-09-18 05:48 UTC, mhilbrunner commented
Merged. Thanks and congrats on your first merged contribution!