Add note for windows laptop to class reference doc
godotengine/godot-docs pull request #8097
Opened 2023-09-29 15:19 UTC by rtflynn

For windows laptops with a 'function' key, F1 actually opens a microsoft edge browser and makes a useless bing query. We can still open the integrated class reference by using 'fn + F1'. Reflect this in the documentation.

2023-09-30 03:58 UTC, skyace65 reviewed
I think this applies to Linux laptops as well, and any windows laptops loaded with Linux. I'll check on mine with a USB tomorrow.

2023-09-30 23:10 UTC, skyace65 requested changes

2023-09-30 23:10 UTC, skyace65 commented on getting_started/introduction/first_look_at_the_editor.rst
> +* Pressing :kbd:`F1` (or :kbd:`Alt + Space` on macOS, or :kbd:`fn + F1` for Windows laptops with a :kbd:`fn` key) anywhere in the editor.
```suggestion
* Pressing :kbd:`F1` (or :kbd:`Alt + Space` on macOS, or :kbd:`fn + F1` for laptops with a :kbd:`fn` key) anywhere in the editor.
```

Just checked and this also applies to Linux laptops.

2023-10-02 15:40 UTC, rtflynn commented
I'm new to git and not sure I'm holding it right. I **think** I added the requested change but not sure if I have to do something more for it to become visible on your end.

2023-10-03 01:10 UTC, skyace65 approved these changes

2023-10-03 01:49 UTC, merged

2023-10-03 01:50 UTC, skyace65 commented
You did it mostly correctly, the change that was needed was applied. For future reference please keep PR's to 1 commit. I can do a squash and merge since this is your first one but please keep it to 1 commit going forward. If you don't know how to do that we have a guide [here](https://docs.godotengine.org/en/stable/contributing/workflow/pr_workflow.html#making-changes). That page also goes over using Git in general so it might be helpful to you for other stuff since you're new to Git.

This PR is failing CI but I'm merging it anyway since you didn't cause that issue, it's from spelling errors on other pages I just fixed in a different PR.

Congrats on your first merged PR!

2023-10-08 23:27 UTC, mhilbrunner commented
Cherry-picked to 4.1