fix #8076, update image and remove note in GDScript warning system docs
godotengine/godot-docs pull request #8136
Opened 2023-10-03 01:39 UTC by Hex-4

closes #8076

This updates the GDScript warning system docs with a new image that doesn't highlight the "advanced" switch and removes the note about having to turn on the "advanced" switch.

2023-10-08 15:17 UTC, Hex-4 commented
Could someone please review this?

2023-10-30 00:11 UTC, Hex-4 commented
Hi! It would be really great if someone could review this before the 31st. @skyace65 I don't know if it's okay to ping people here, but it would be nice if you could spare a minute and review this.

2023-10-30 17:06 UTC, AThousandShips commented
What's the rush?

We're currently prioritising releasing 4.2 so reviews might be slow

2023-11-05 14:48 UTC, skyace65 requested changes
Removing the note completely without any mention of needing to search for the gdscript section is just going to confuse more people.  The existing note should just be updated with another sentence saying "you can also search for the section if advanced settings is off" or something like that.

2023-11-06 23:46 UTC, Hex-4 commented
Thanks for the review! I just pushed a change that hopefully fixes it - should I undo the image change?

2023-11-07 03:07 UTC, skyace65 commented
Yes, revert to the original image and this should be good to go.

2023-11-08 23:28 UTC, skyace65 approved these changes

2023-11-08 23:30 UTC, merged

2023-11-08 23:30 UTC, skyace65 commented
Thanks!

2023-11-08 23:48 UTC, Hex-4 commented
Great! Sorry for bugging you a little before hehe