Fixed some errors in C# examples.
godotengine/godot-docs pull request #8143
Opened 2023-10-03 13:30 UTC by nbourre

2023-10-03 13:40 UTC, raulsntos reviewed
Thanks for contributing to the .NET documentation! Your fixes are looking great.

It looks like the example is using tabs for indentation, but we use spaces in the documentation.

Also, while you are editing this page, could you also fix the example in the _Controlling an AnimationPlayer animation_ section? The `_Process` method is still using `float` instead of `double`.

2023-10-03 13:40 UTC, raulsntos commented on tutorials/2d/2d_sprite_animation.rst
> +    public partial class Player : CharacterBody2D
For C# class names we usually follow this pattern: `My{BASE_CLASS_NAME}`:

```suggestion
    public partial class MyCharacterBody2D : CharacterBody2D
```

2023-10-04 01:16 UTC, nbourre commented
Sure, I’ll fix the other example tomorrow.

2023-10-06 11:08 UTC, raulsntos requested changes

2023-10-06 11:08 UTC, raulsntos commented on tutorials/2d/2d_sprite_animation.rst
> +    	}
Use spaces for indentation.

```suggestion
        private AnimatedSprite2D _animatedSprite;

        public override void _Ready()
        {
            _animatedSprite = GetNode<AnimatedSprite2D>("AnimatedSprite2D");
        }

        public override void _Process(double delta)
        {
            if (Input.IsActionPressed("ui_right"))
            {
                _animatedSprite.Play("run");
            }
            else
            {
                _animatedSprite.Stop();
            }
        }
```

2023-10-06 11:08 UTC, raulsntos commented on tutorials/2d/2d_sprite_animation.rst
> +        public override void _Process(double _delta)
The `delta` parameter name should match the base declaration, even if unused. Sorry that I didn't mention this before, I missed it.

```suggestion
        public override void _Process(double delta)
```

2023-10-06 11:08 UTC, raulsntos commented on tutorials/audio/sync_with_audio.rst
> +    public override void _Process(double _delta)
```suggestion
    public override void _Process(double delta)
```

2023-10-06 11:08 UTC, raulsntos commented on tutorials/audio/sync_with_audio.rst
> +    public override void _Process(double _delta)
```suggestion
    public override void _Process(double delta)
```

2025-02-05 19:18 UTC, tetrapod00 commented
Superseded by https://github.com/godotengine/godot-docs/pull/10624. (The `AnimatedSprite2D` rename was already done at some point.)

2025-02-05 19:18 UTC, closed without merging