Fixing small wrong info
godotengine/godot-docs pull request #8267
Opened 2023-10-18 09:23 UTC by rhogeranacleto

The docs says to includes the `get_tree().call_group("mobs", "queue_free")` to the `new_game()` when is actually to the `gamer_over()`

2023-10-18 09:26 UTC, AThousandShips reviewed
Please make your changes with `git commit --amend` to keep it a single commit

2023-10-18 09:26 UTC, AThousandShips commented on getting_started/first_2d_game/06.heads_up_display.rst
> +the ``gamer_over()`` function in ``Main``:
```suggestion
the ``game_over()`` function in ``Main``:
```

2023-10-22 02:40 UTC, skyace65 requested changes
The 2D dodge the creeps project in the demo repository does have that line of code in ``new_game()`` and not ``game_over()`` and I don't see anything else in the docs suggesting that line of code should be in the game over function. What are you looking at that implies this is the wrong place to put it?

2023-10-22 08:47 UTC, AThousandShips commented
Could be confusion over that `new_game` comes after `game_over`, when I skimmed the file I thought the change was correct for that reason I believe

2023-10-23 10:31 UTC, rhogeranacleto commented
It could be my beginner's feeling about how this works.
When I put that line on the new game the Mob's stays on screen until I click on new_game button, which sometimes the 3-second timeout is not enough to destroy all remaining enemies, and it feels like the game isn't actually finished.
But I understand your point. You can close this PR then.

2023-10-23 10:32 UTC, closed without merging