Document integer scaling support in Multiple resolutions
godotengine/godot-docs pull request #8298
Opened 2023-10-21 08:51 UTC by Calinou

This also adds more recommendations for base viewport sizes in pixel art games.

Don't cherry-pick, as this feature is only in 4.2.

- See https://github.com/godotengine/godot/pull/75784 and https://github.com/godotengine/godot-demo-projects/pull/985.

2023-10-21 09:58 UTC, Piralein requested changes

2023-10-21 09:58 UTC, Piralein commented on tutorials/rendering/multiple_resolutions.rst
> +stretch scale mode set to ``integer``:
```suggestion
stretch scale mode is set to ``integer``:
```

2023-10-21 22:36 UTC, skyace65 approved these changes

2023-10-21 22:36 UTC, skyace65 commented
This will supersede #8231.

2023-10-22 08:58 UTC, mhilbrunner approved these changes

2023-10-22 08:59 UTC, merged

2023-10-22 08:59 UTC, mhilbrunner commented
Thanks! Merged.