Fixed typos in custom_performance_monitors.rst
godotengine/godot-docs pull request #8340
Opened 2023-10-27 13:48 UTC by NoctemCat

Changed Monitor to Monitors and added missing colon in the link to Performance.add_custom_monitor

2023-10-31 01:06 UTC, skyace65 requested changes
Just needs one minor change to make a sentence sound better. other than that this looks good!

2023-10-31 01:06 UTC, skyace65 commented on tutorials/scripting/debug/custom_performance_monitors.rst
> +Since Godot 4.0, you can declare custom values to be displayed in this Monitors
```suggestion
Since Godot 4.0, you can declare custom values to be displayed in the Monitors
```

2023-10-31 02:29 UTC, NoctemCat commented
Hello. Have I changed it correctly? And also set resolved

2023-10-31 21:54 UTC, skyace65 approved these changes

2023-10-31 21:54 UTC, merged

2023-10-31 21:54 UTC, skyace65 commented
You did change it correctly, thanks! And congrats on your first merged PR!

2023-11-11 04:41 UTC, mhilbrunner commented
Cherry-picked to 4.1.