Add "Upgrading from Godot 4.1 to Godot 4.2" page
godotengine/godot-docs pull request #8488
Opened 2023-11-16 18:19 UTC by raulsntos

Adds the migration guide for 4.2, just like we did for 4.1 (https://github.com/godotengine/godot-docs/pull/7611).

Last time we didn't include GDExtension compatibility because 4.1 completely broke compatibility, we added a warning at the top of the page instead. I'm not sure how we want to handle GDExtension compatibility this time, the @godotengine/gdextension team can suggest changes or make a follow-up PR.

Area maintainers should review the changes listed for their area. Also feel free to suggest any addition that I might have missed or make follow-up PRs.

2023-11-17 11:18 UTC, Calinou commented on tutorials/migrating/upgrading_to_godot_4.2.rst
> +This article indicates whether each breaking change affects GDScript and whether
Add section on Mesh format compatibility:

```suggestion
affect you. Changes are grouped by areas/systems.

.. warning::

    The Mesh resource format has changed in 4.2 to allow for
    `vertex and attribute compression <https://github.com/godotengine/godot/pull/81138>`__. This allows for improved rendering performance, especially
    on platforms constrained by memory bandwidth such as mobile.
	
    It is still possible to load the Godot 4.0-4.1 Mesh formats, but it is
    **not** possible to load the Godot 4.2 Mesh format in prior Godot versions.
    When opening a project, you will be presented with an upgrade dialog that has two options:
	
    - **Restart & Upgrade:** This prevents downgrading the project to a Godot version
      older than 4.2. Set up a version control system and push your changes
      *before* choosing this option!
    - **Upgrade Only:** Upgrades the mesh format in-memory without writing it
      to disk. This allows downgrading the project to a Godot version older than 4.2
      if you need to do so in the future. The downside is that loading the project
      will be slower every time as the mesh format needs to be upgraded every time
      the project is loaded. These increased loading times will also affect the
      exported project. The number and complexity of Mesh resources determines
      how much loading times are be affected.

This article indicates whether each breaking change affects GDScript and whether
```

2023-11-20 17:53 UTC, Calinou commented on tutorials/migrating/upgrading_to_godot_4.2.rst
> +      how much loading times are be affected.
```suggestion
.. warning::

    The :ref:`class_Mesh` resource format has changed in 4.2 to allow for
    `vertex and attribute compression <https://github.com/godotengine/godot/pull/81138>`__.
    This allows for improved rendering performance, especially on platforms
    constrained by memory bandwidth such as mobile.

    It is still possible to load the Godot 4.0-4.1 Mesh formats, but it is
    **not** possible to load the Godot 4.2 Mesh format in prior Godot versions.
    When opening a Godot project made with a version prior to 4.2, you may
    be presented with an upgrade dialog that offers two options:

    - **Restart & Upgrade:** Upgrades the mesh format for all meshes in the
      project and saves the result to disk. Once chosen, this option prevents
      downgrading the project to a Godot version prior to 4.2. Set up a
      version control system and push your changes *before* choosing this option!
    - **Upgrade Only:** Upgrades the mesh format in-memory without writing it
      to disk. This allows downgrading the project to a Godot version older than 4.2
      if you need to do so in the future. The downside is that loading the project
      will be slower every time as the mesh format needs to be upgraded every time
      the project is loaded. These increased loading times will also affect the
      exported project. The number and complexity of Mesh resources determines
      how much loading times are be affected.
    
    If this dialog doesn't appear, use **Project > Tools > Upgrade Mesh Surfaces…**
    at the top of the editor.
```

2023-11-20 18:27 UTC, Cerno-b requested changes
I just did a language review, I have no clue about content accuracy ;)

2023-11-20 18:27 UTC, Cerno-b commented on tutorials/migrating/upgrading_to_godot_4.2.rst
> +      how much loading times are be affected.
Typo "are be"

2023-11-20 18:27 UTC, Cerno-b commented on tutorials/migrating/upgrading_to_godot_4.2.rst
> +Signal ``close_request`` renamed to``delete_request`` and moved to base class ``GraphElement``                            |❌|                 |✔️ with compat|      |✔️ with compat|      `GH-79311`_
space missing before ``delete_request``

2023-11-20 19:26 UTC, AThousandShips commented on tutorials/migrating/upgrading_to_godot_4.2.rst
> +Method ``find_variation`` adds new ``spacing_top``, ``spacing_bottom``, ``spacing_space`` and ``spacing_glyph`` optional parameters   |✔️|                 |✔️ with compat|      |✔️|
```suggestion
Method ``find_variation`` adds new ``spacing_top``, ``spacing_bottom``, ``spacing_space``, and ``spacing_glyph`` optional parameters   |✔️|                 |✔️ with compat|      |✔️|                  `GH-80954`_
```
Please use [Oxford comma](https://docs.godotengine.org/en/latest/contributing/documentation/docs_writing_guidelines.html#use-the-oxford-comma-to-enumerate-anything).

2023-11-20 19:26 UTC, AThousandShips commented on tutorials/migrating/upgrading_to_godot_4.2.rst
> +Method ``add_image`` adds new ``key``, ``pad``, ``tooltip`` and ``size_in_percent`` optional parameters                   |✔️|                 |✔️ with compat|      |✔️|                  `GH-80410`_
```suggestion
Method ``add_image`` adds new ``key``, ``pad``, ``tooltip``, and ``size_in_percent`` optional parameters                   |✔️|                 |✔️ with compat|      |✔️|                  `GH-80410`_
```

2023-11-21 00:06 UTC, skyace65 approved these changes

2023-11-21 07:56 UTC, mhilbrunner approved these changes

2023-11-21 07:56 UTC, merged

2023-11-21 07:56 UTC, mhilbrunner commented
Thank you! Merged.