Add section on optimizing distribution size in Optimizing a build for size
godotengine/godot-docs pull request #8500
Opened 2023-11-18 11:45 UTC by Calinou

This isn't strictly related to compiling custom export templates, but it's a neat trick to reduce the final distribution size that works regardless of the export template binary used.

2023-11-18 12:02 UTC, mhilbrunner approved these changes

2023-11-19 15:50 UTC, skyace65 requested changes
Only one issue, everything else looks good

2023-11-19 15:50 UTC, skyace65 commented on contributing/development/compiling/optimizing_for_size.rst
> +signifcantly, leading to faster loading times, especially on slow connections.
```suggestion
significantly, leading to faster loading times, especially on slow connections.
```

2023-11-24 21:04 UTC, skyace65 approved these changes

2023-11-24 21:04 UTC, merged

2023-11-24 21:04 UTC, skyace65 commented
Thanks!