Update
godotengine/godot-docs pull request #8648
Opened 2023-12-19 02:30 UTC by heinrichstr

Update OS.min_screen_size to DisplayServer.window_set_min_size() in [multiple_resolutions.rst](https://docs.godotengine.org/en/latest/tutorials/rendering/multiple_resolutions.html#non-game-application) as min screen size was moved to DisplayServer in 4.0.

This is my first pull request, so apologies if I messed up any parts of this.

2023-12-19 06:54 UTC, AThousandShips requested changes
Thank you for your contribution!

You have made changes to files that you shouldn't do you need to fix this

This is because you started your branch from 4.2 instead of master, see [here](https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html#rebasing-onto-another-branch) for instructions, I can fix it for you if you are unable to

2023-12-19 06:54 UTC, AThousandShips commented on .github/workflows/sync_class_ref.yml
This file should not be changed

2023-12-19 06:54 UTC, AThousandShips commented on conf.py
Or this one

2023-12-19 06:54 UTC, AThousandShips commented on index.rst
Or this one

2023-12-19 09:26 UTC, AThousandShips commented
I went ahead and fixed this for you 🙂

2023-12-19 09:27 UTC, AThousandShips commented on tutorials/rendering/multiple_resolutions.rst
> +- You can define a minimum window size by setting ``DisplayServer.window_set_min_size()`` in a
```suggestion
- You can define a minimum window size by calling ``DisplayServer.window_set_min_size()`` in a
```
As `setting` doesn't apply for a method in this case

2023-12-20 18:51 UTC, heinrichstr commented
> I went ahead and fixed this for you 🙂

Thank you! <3

2023-12-21 12:56 UTC, Piralein commented
We should perhaps use the recommended way outlined in [DisplayServer.xml](https://github.com/godotengine/godot/blob/master/doc/classes/DisplayServer.xml#L1520).

`get_window().set_min_size()`

2024-04-08 13:46 UTC, mhilbrunner commented
Thanks for contributing! This has been superseded by https://github.com/godotengine/godot-docs/pull/9049.

2024-04-08 13:46 UTC, closed without merging