Fixed typo in pr_workflow.rst
godotengine/godot-docs pull request #8671
Opened 2023-12-22 22:19 UTC by ramadm

2023-12-24 15:07 UTC, skyace65 requested changes
I'd get rid of the "of" in that sentence to make it sound better.

2023-12-24 15:07 UTC, skyace65 commented on contributing/workflow/pr_workflow.rst
> +aware of our workflow and Git usage tips, reviewers might request of you to
```suggestion
aware of our workflow and Git usage tips, reviewers might request you to
```

2023-12-26 22:31 UTC, ramadm commented
Hi, I committed your change. I see that the docs suggested to keep changes to a single commit when possible, but I'm not sure if it's possible to do that via GitHub's online editor. If you want me to delete and re-submit the PR as a single commit let me know.

2023-12-26 22:37 UTC, AThousandShips commented
It's okay in this case, but in the future please use the computer setup, just editing from the web interface is very limited 🙂

2023-12-27 02:20 UTC, skyace65 approved these changes

2023-12-27 02:49 UTC, merged

2023-12-27 02:52 UTC, skyace65 commented
I've done a squash and merge for this PR so it's only 1 commit, but in the future I'd highly recommend getting setup with a proper editor on your computer for using Git. If you don't know anything about Git we have a guide in the Godot docs [here](https://docs.godotengine.org/en/stable/contributing/workflow/pr_workflow.html).

Also congrats on your first merged PR!

2024-01-25 08:57 UTC, mhilbrunner commented
Cherry-picked to 4.2.