Update scripting_player_input.rst
godotengine/godot-docs pull request #8722
Opened 2024-01-05 05:56 UTC by kylestarr

Commenting out code from the previous exercise that causes the icon to float up, making it difficult for users to see the example of directional input.

2024-01-06 11:04 UTC, AThousandShips commented on getting_started/step_by_step/scripting_player_input.rst
> +    // Position += velocity * (float)delta;
```suggestion
    //var velocity = Vector2.Up.Rotated(Rotation) * _speed;

    //Position += velocity * (float)delta;
```
Commented out code has no leading space, like in GDScript

2024-01-23 02:05 UTC, skyace65 requested changes
You need to tell people to un-comment the ``Position`` line in the next section, otherwise that code doesn't work.

2024-01-23 02:05 UTC, skyace65 commented on getting_started/step_by_step/scripting_player_input.rst
> +Comment out the lines ``var velocity = Vector2.UP.rotated(rotation) * speed`` and ``position += velocity * delta`` with the code below:
```suggestion
Comment out the lines ``var velocity = Vector2.UP.rotated(rotation) * speed`` and ``position += velocity * delta`` like this:
```
the phrasing "with the code below" sounds weird to me.

2024-01-26 04:34 UTC, kylestarr commented on getting_started/step_by_step/scripting_player_input.rst
> +velocity. Uncomment the code and replace the line starting with ``var velocity`` with the code below.
@skyace65 I've made a simple update that accounts for both comments.

2024-01-27 12:45 UTC, skyace65 approved these changes

2024-02-04 21:51 UTC, merged

2024-02-04 21:51 UTC, skyace65 commented
Thanks!

2024-07-24 19:38 UTC, mhilbrunner commented
Cherry-picked to 4.2 in https://github.com/godotengine/godot-docs/pull/9648.