Moving disclaimer comments inline
godotengine/godot-docs pull request #8832
Opened 2024-01-26 05:04 UTC by kylestarr

Moving disclaimer comments inline to better specify which boolean statement is being referred to.

2024-01-26 05:59 UTC, mhilbrunner commented on getting_started/first_2d_game/03.coding_the_player.rst
> +            $AnimatedSprite2D.flip_h = velocity.x < 0 ## See the note below about this boolean assignment.
```suggestion
            $AnimatedSprite2D.flip_h = velocity.x < 0 # See the note below about this boolean assignment.
```

2024-01-26 09:31 UTC, YuriSizov commented
I don't think this helps to better specify. It doesn't change which line the comment refers to, it just makes the snippet much wider, which is a problem for codeblocks in samples. So IMO this just makes it harder to read the docs.

2024-01-27 05:07 UTC, kylestarr commented
> I don't think this helps to better specify. It doesn't change which line the comment refers to, it just makes the snippet much wider, which is a problem for codeblocks in samples. So IMO this just makes it harder to read the docs.

@YuriSizov That is fair. And I had considered that when creating this PR. Perhaps the better direction is to simply add to the comment that it's referring to the boolean statement below rather than the one prior. See new commit https://github.com/godotengine/godot-docs/pull/8832/commits/af66da052fb276ad2d5182888d71fa99515abc3b

2024-02-23 22:55 UTC, skyace65 approved these changes

2024-02-23 22:56 UTC, skyace65 requested changes

2024-02-23 22:56 UTC, skyace65 commented on getting_started/first_2d_game/03.coding_the_player.rst
> +            ## See the note below about the following boolean assignment.
```suggestion
            # See the note below about the following boolean assignment.
```

2024-02-28 23:08 UTC, skyace65 approved these changes

2024-02-28 23:08 UTC, merged

2024-02-28 23:08 UTC, skyace65 commented
Thanks!

2024-07-24 18:39 UTC, mhilbrunner commented
Cherry-picked to 4.2 in https://github.com/godotengine/godot-docs/pull/9647.