Configure ignoring object and library files in CLion
godotengine/godot-docs pull request #8991
Opened 2024-02-18 18:05 UTC by catwasd

This PR adds a new section to configure ignoring object and library files (*.a, *.o) in the Project view of CLion. This is helpful as it can make the Project view cleaner after Godot is built.

<img height=400 src="https://github.com/godotengine/godot-docs/assets/128197903/298a2ff7-1d79-4b26-bab7-f1eca00f0853">

2024-02-23 01:32 UTC, skyace65 requested changes
Please convert the images in this PR to webp format, I'd recommend doing that with squoosh (https://squoosh.app/). And please use lossless compression.

2024-02-23 02:44 UTC, catwasd commented
Thanks. Updated with lossless webp image files.

2025-01-21 22:18 UTC, skyace65 approved these changes

2025-01-21 22:18 UTC, merged

2025-01-21 22:18 UTC, skyace65 commented
Thanks! Apologies on the long merge time