Add intellisense configuration for VSCode
godotengine/godot-docs pull request #9116
Opened 2024-03-18 23:57 UTC by kitbdev

- closes https://github.com/godotengine/godot-docs/issues/7298
- closes https://github.com/godotengine/godot-docs/issues/8307
- closes https://github.com/godotengine/godot-docs/issues/7218

Added a Configuring Intellisense section for VSCode to address common issues with include errors: 
\# include errors detected. cannot open source file "alloca.h"

Only added examples for Windows, since as far as I know its only a problem on Windows.

There are two ways to fix the issue users have (as far as I know):
1. Setting the `includePath`, `defines`, and `compilerPath` setting in `c_cpp_properties.json`.
2. Using `compiledb=yes` scons arg and  setting the `compileCommands` setting in `c_cpp_properties.json`.

The first way is preferred since if any files are added or changed (including when switching branches in some cases) you will need to recompile to recreate the `compile_commands.json` file.

Added image for the commands to edit the file, since the page has similar. Those commands are important since they can generate the file if it does not already exist.

2024-03-19 00:49 UTC, skyace65 requested changes
Please change the image you added from a png to a webp. I'd recommend converting it with [squoosh](https://squoosh.app/) online, and please keep the image lossless. Also when updating this PR please keep everything to 1 commit, if you don't know how to do that we have a guide [here](https://docs.godotengine.org/en/stable/contributing/workflow/pr_workflow.html#modifying-a-pull-request).

2024-03-19 01:17 UTC, skyace65 reviewed
Thanks for updating the image!

2024-03-19 13:15 UTC, skyace65 approved these changes

2024-03-22 05:50 UTC, mhilbrunner approved these changes

2024-03-22 05:53 UTC, mhilbrunner commented on contributing/development/configuring_an_ide/visual_studio_code.rst
> +---------------------
```suggestion
Configuring Intellisense
------------------------
```

2024-03-22 18:31 UTC, merged

2024-03-22 18:31 UTC, mhilbrunner commented
Merged. Thanks and congrats on your first merged contribution!

2024-07-24 19:36 UTC, mhilbrunner commented
Cherry-picked to 4.2 in https://github.com/godotengine/godot-docs/pull/9648.