Updated Resources tutorial to mention and use the GlobalClass annotation for C#
godotengine/godot-docs pull request #9278
Opened 2024-04-25 05:31 UTC by j4d3blooded

The previous version of this page didn't mention using the `[GlobalClass]` annotation. Following this tutorial results in the user not finding their resource in the Create a new resource menu without any understanding as to why

2024-04-25 06:34 UTC, paulloz requested changes
Thank you!

2024-04-25 06:34 UTC, paulloz commented on tutorials/scripting/resources.rst
> +    If you're using C#, you need to annoate your Resource class with the ``[GlobalClass]`` annotation for it to show up in the create resource GUI.
```suggestion
    If you're using C#, you need to annotate your Resource class with the ``[GlobalClass]`` attribute for it to show up in the create resource GUI.
```

This is called an attribute in C#, not an annotation.

2024-04-27 06:45 UTC, paulloz approved these changes

2024-04-28 08:51 UTC, AThousandShips commented on tutorials/scripting/resources.rst
> +        [GlobalClass]
```suggestion

        [GlobalClass]
```

2024-04-28 08:52 UTC, AThousandShips requested changes
Thank you for your contribution!

You should target `master` not `4.2`, changes can then be cherry picked, see [here](https://docs.godotengine.org/en/latest/contributing/documentation/contributing_to_the_documentation.html#contributing-changes).

You can rebase it to fix it, or open a new one, see [here](https://docs.godotengine.org/en/stable/contributing/workflow/pr_workflow.html#rebasing-onto-another-branch)

2024-04-29 01:19 UTC, j4d3blooded commented
I'm not entirely sure how I would go about fixing merge commits or cherry picking the relevant changes from this point, sorry

2024-04-29 07:52 UTC, AThousandShips approved these changes

2024-04-29 07:52 UTC, AThousandShips commented
There, it works now, just had to change the target as well, thank you!

2024-04-30 02:16 UTC, mhilbrunner approved these changes

2024-04-30 02:16 UTC, merged

2024-04-30 02:16 UTC, mhilbrunner commented
Merged. Thanks and congrats on your first merged contribution!