Update NavigationObstacles for Godot 4.3 changes
godotengine/godot-docs pull request #9336
Opened 2024-05-06 17:50 UTC by smix8

Updates NavigationObstacles documentation as they can not affect the navigation mesh baking.

Those changes are only in Godot 4.3 so no need to backport.

Also added an animation for the dynamic obstacles as users had a difficult time to grasp what they do from text alone.

2024-05-06 18:05 UTC, AThousandShips commented on tutorials/navigation/navigation_using_navigationobstacles.rst
> +With enough created save space around the obstacle it should add the static vertices again and remove the radius.
```suggestion
With enough created safe space around the obstacle it should add the static vertices again and remove the radius.
```

2024-05-06 18:05 UTC, AThousandShips commented on tutorials/navigation/navigation_using_navigationobstacles.rst
> +This helps to avoid getting agents stuck in the suddenly appearing static obstacle when the rebuild static boundary is finished.
```suggestion
This helps to avoid getting agents stuck in the suddenly appearing static obstacle when the rebuilt static boundary is finished.
```

2024-05-06 18:05 UTC, AThousandShips commented on tutorials/navigation/navigation_using_navigationobstacles.rst
> +- Static obstacles can not change their position. They can only be warped to a new position and rebuild from scratch.
```suggestion
- Static obstacles can not change their position. They can only be warped to a new position and rebuilt from scratch.
```

2024-05-06 18:05 UTC, AThousandShips commented on tutorials/navigation/navigation_using_navigationobstacles.rst
> +   Navigation agents deterred by a dynamic navigation obstacle's radius
```suggestion
   Navigation agents deterred by a dynamic navigation obstacle's radius.
```

2024-05-06 18:05 UTC, AThousandShips commented on tutorials/navigation/navigation_using_navigationobstacles.rst
> +Navigation obstacles are dual purpose in that they can affected both the navigation mesh baking and the agent avoidance.
```suggestion
Navigation obstacles are dual purpose in that they can affect both the navigation mesh baking and the agent avoidance.
```

2024-05-07 09:30 UTC, mhilbrunner commented
Didn't do an in-depth review yet (but trust ATS anyway :)) but this looks good to me so far. I wonder whether we consider 0.8mb OK for the gif - I guess its fine by this day and age? (Maybe @Calinou has some magic alternative to get it down further?)

2024-05-08 01:52 UTC, skyace65 commented
> Didn't do an in-depth review yet (but trust ATS anyway :)) but this looks good to me so far. I wonder whether we consider 0.8mb OK for the gif - I guess its fine by this day and age? (Maybe @Calinou has opinions or some magic alternative to get it down further?)

I just tried using Kdenlive but the output ends up being bigger than the original.

2024-05-14 18:15 UTC, smix8 commented
Removed the animation.

2024-05-15 23:08 UTC, skyace65 requested changes

2024-05-15 23:08 UTC, skyace65 commented on tutorials/navigation/navigation_using_navigationobstacles.rst
> +New obstacles can be created in script without a Node by using the NavigationServer directly.
```suggestion
New obstacles can be created in a script without a Node by using the NavigationServer directly.
```

2024-05-15 23:08 UTC, skyace65 commented on tutorials/navigation/navigation_using_navigationobstacles.rst
> +Navigation obstacles are dual purpose in that they can affect both the navigation mesh baking and the agent avoidance.
```suggestion
Navigation obstacles are dual purpose in that they can affect both the navigation mesh baking, and the agent avoidance.
```

2024-05-15 23:08 UTC, skyace65 commented on tutorials/navigation/navigation_using_navigationobstacles.rst
> +The obstacle shape and placement is defined with the ``height`` and ``vertices`` properties and the ``global_position`` of the obstacle.
```suggestion
The obstacle shape and placement is defined with the ``height`` and ``vertices`` properties, and the ``global_position`` of the obstacle.
```

2024-05-15 23:08 UTC, skyace65 commented on tutorials/navigation/navigation_using_navigationobstacles.rst
> +For baking navigation mesh in scripts obstacles can be added procedural as a projected obstruction.
```suggestion
When baking navigation meshes in scripts obstacles can be added procedurally as a projected obstruction.
```

2024-05-15 23:08 UTC, skyace65 commented on tutorials/navigation/navigation_using_navigationobstacles.rst
> +  Static obstacles as a result are ill-suited for usages where the position is changed every frame as the constant rebuild has a high performance cost.
```suggestion
  Static obstacles as a result are ill-suited for usages where the position is changed every frame, as the constant rebuild has a high performance cost.
```

2024-05-15 23:08 UTC, skyace65 commented on tutorials/navigation/navigation_using_navigationobstacles.rst
> +This helps to avoid getting agents stuck in the suddenly appearing static obstacle when the rebuilt static boundary is finished.
```suggestion
This helps avoid getting agents stuck in the suddenly appearing static obstacle when the rebuilt static boundary is finished.
```

2024-05-16 21:48 UTC, skyace65 approved these changes

2024-05-18 00:05 UTC, mhilbrunner approved these changes

2024-06-03 22:20 UTC, merged

2024-06-03 22:20 UTC, skyace65 commented
Thanks!