Update the Android documentation for Godot 4.3
godotengine/godot-docs pull request #9371
Opened 2024-05-13 20:15 UTC by m4gr3d

- Update the Android dependencies versions following https://github.com/godotengine/godot/pull/87346
- Remove the section about creating the `debug.keystore` following https://github.com/godotengine/godot/pull/90611

2024-05-14 00:03 UTC, skyace65 requested changes
This looks good. The image just needs to be converted from a png to a webp. I'd recommend using [squoosh](https://squoosh.app/), just use maximum lossless compression.

2024-05-15 22:49 UTC, skyace65 approved these changes

2024-05-15 22:50 UTC, merged

2024-05-15 22:50 UTC, skyace65 commented
Thanks!

2024-06-06 15:41 UTC, AThousandShips commented
Some of these changes need a 4.2 version as https://github.com/godotengine/godot/pull/87346 was cheery picked