Rewrite OpenXR hand tracking to reflect new architecture
godotengine/godot-docs pull request #9499
Opened 2024-06-17 14:17 UTC by BastiaanOlij

Work in progress, I'm rewriting the hand tracking manual page to reflect the new way things are structured in Godot 4.3.
About half way done.

Note that this manual page references https://github.com/godotengine/godot-demo-projects/pull/973 and that PR needs to be merged alongside this.

2024-06-17 14:18 UTC, BastiaanOlij commented on tutorials/xr/openxr_hand_tracking.rst
> +**replace this image with an updated one**
Reminder to self, need to do this.

2024-06-18 10:48 UTC, AThousandShips commented on tutorials/xr/openxr_body_tracking.rst
> +=====================
```suggestion
====================
```

2024-06-18 10:48 UTC, AThousandShips commented on tutorials/xr/openxr_hand_tracking.rst
> +You may find yourself in a place where chosen hardware doesn't support a piece of the puzzle or does things different
```suggestion
You may find yourself in a place where chosen hardware doesn't support a piece of the puzzle or does things differently
```

2024-06-18 10:48 UTC, AThousandShips commented on tutorials/xr/openxr_hand_tracking.rst
> +is a new core extension which supports pinch, grasp and poke gestures and related poses.
```suggestion
is a new core extension which supports pinch, grasp, and poke gestures and related poses.
```

2024-06-18 10:48 UTC, AThousandShips commented on tutorials/xr/openxr_hand_tracking.rst
> +If there is a tracker but `has_tracking_data` is false, the users hand is currently not being tracked.
```suggestion
If there is a tracker but `has_tracking_data` is false, the user's hand is currently not being tracked.
```

2024-06-18 10:48 UTC, AThousandShips commented on tutorials/xr/openxr_hand_tracking.rst
> +More recently optical hand tracking has become a popular solution, where cameras track the users hands
```suggestion
More recently optical hand tracking has become a popular solution, where cameras track the user's hands
```

2024-06-18 10:48 UTC, AThousandShips commented on tutorials/xr/openxr_hand_tracking.rst
> +users palm is facing away from the user.
```suggestion
user's palm is facing away from the user.
```

2024-06-18 10:48 UTC, AThousandShips commented on tutorials/xr/openxr_hand_tracking.rst
> +are touching while the users palm is facing towards the user.
```suggestion
are touching while the user's palm is facing towards the user.
```

2024-06-18 10:48 UTC, AThousandShips commented on tutorials/xr/openxr_hand_tracking.rst
> +The hand tracking system uses separate hand trackers to track the position of the players hands
```suggestion
The hand tracking system uses separate hand trackers to track the position of the player's hands
```

2024-06-18 10:48 UTC, AThousandShips commented on tutorials/xr/openxr_hand_tracking.rst
> +traditionally it was left up to the game to implement a mechanism to display the players hand and animate
```suggestion
From the tracking data we can infer the location of the player's hands but no further information is known,
traditionally it was left up to the game to implement a mechanism to display the player's hand and animate
```

2024-06-18 10:48 UTC, AThousandShips commented on tutorials/xr/openxr_hand_tracking.rst
> +    avatar creation UIs, fake mirrors or similar situations
```suggestion
    avatar creation UIs, fake mirrors, or similar situations
```

2024-06-18 16:42 UTC, dsnopek reviewed
Thanks! This looks great!

I only have a couple language nit-picks.

2024-06-18 16:42 UTC, dsnopek commented on tutorials/xr/openxr_hand_tracking.rst
> +and full tracked data for the hand and finger position became available.
```suggestion
and full tracking data for the hand and finger positions becomes available.
```

2024-06-18 16:42 UTC, dsnopek commented on tutorials/xr/openxr_hand_tracking.rst
> +access hand and finger position and orientation data.
```suggestion
access hand and finger positions and orientation data.
```

2024-06-18 16:42 UTC, dsnopek commented on tutorials/xr/openxr_hand_tracking.rst
> +When handling input it was up to the game developer to implement a gesture detection mechanism.
```suggestion
When handling input, it was up to the game developer to implement a gesture detection mechanism.
```

2024-06-18 16:42 UTC, dsnopek commented on tutorials/xr/openxr_hand_tracking.rst
> +The information presented on this page was used to create a demo projection that can be found
```suggestion
The information presented on this page was used to create a demo project that can be found
```

2024-06-18 16:42 UTC, dsnopek commented on tutorials/xr/openxr_hand_tracking.rst
> +The hand tracking implementation in Godot has been standardised around the Godot Humanoid Skeleton
Probably not important, but I think we try to use US (vs UK) spellings:

```suggestion
The hand tracking implementation in Godot has been standardized around the Godot Humanoid Skeleton
```

2024-06-18 16:42 UTC, dsnopek commented on tutorials/xr/openxr_hand_tracking.rst
> +    resulting in the hand mesh and finger tracking being localised elsewhere.
Another US vs UK spelling:

```suggestion
    resulting in the hand mesh and finger tracking being localized elsewhere.
```

2024-06-18 16:42 UTC, dsnopek commented on tutorials/xr/openxr_hand_tracking.rst
> +Recognising that there is an increasing demand for applications that can switch seamlessly
US vs UK spelling:

```suggestion
Recognizing that there is an increasing demand for applications that can switch seamlessly
```

2024-06-19 02:03 UTC, BastiaanOlij commented
I think I got all the reported grammar issue, thanks for the proof reading @AThousandShips and @dsnopek

2024-06-19 13:20 UTC, dsnopek approved these changes

2024-06-19 16:03 UTC, AThousandShips approved these changes

2024-06-19 16:25 UTC, skyace65 requested changes

2024-06-21 00:19 UTC, skyace65 approved these changes

2024-06-23 08:10 UTC, mhilbrunner approved these changes

2024-06-24 17:21 UTC, m4gr3d approved these changes

2024-06-25 11:07 UTC, BastiaanOlij commented
Thanks for the approvals everyone, please also check out the demo project that accompanies this.

2024-06-26 04:05 UTC, skyace65 commented
I can check that the demo runs on my computer later this week. Unfortunately though my headset doesn't have hand tracking.

2024-06-26 04:11 UTC, BastiaanOlij commented
> I can check that the demo runs on my computer later this week. Unfortunately though my headset doesn't have hand tracking.

If you have steamVR it'll work on inferred hand tracking, all should still work :)

2024-06-29 13:07 UTC, mhilbrunner commented
This PR is good to go and just waiting on the demo to be merged. Unfortunately, I currently lack the bandwith to check it out myself. Please poke me once that PR is merged so we can merge this one :)

2024-07-13 19:05 UTC, merged

2024-07-13 19:05 UTC, skyace65 commented
XR Demo is merged as well. Thanks for your work on both of these!