First look at editor's interface iteration
godotengine/godot-docs pull request #9553
Opened 2024-06-28 08:16 UTC by vgezer

Updated screenshots, renamed AssetLib to Asset Library, also changed the structure to ease readability. Removed some detailed stuff and pointed to the other documents since this is only the first look. Detailed project manager screen.

Open for comments.

2024-06-28 11:53 UTC, AThousandShips commented
I'd suggest perhaps splitting this into multiple PRs for each area of the documentation, as it touches on pretty different areas

2024-06-28 12:03 UTC, AThousandShips commented on getting_started/introduction/first_look_at_the_editor.rst
> +.. seealso:: To learn more on 3D viewport and 3D in general, read :ref:`doc_introduction_to_3d`.
```suggestion
.. seealso:: To learn more on the 3D viewport and 3D in general, read :ref:`doc_introduction_to_3d`.
```

2024-06-28 12:03 UTC, AThousandShips commented on getting_started/introduction/first_look_at_the_editor.rst
> +From here, you can change the editor's language (default is system language), interface theme, display
```suggestion
From here, you can change the editor's language (default is the system language), interface theme, display 
```

2024-06-28 12:03 UTC, AThousandShips commented on getting_started/introduction/first_look_at_the_editor.rst
> +Project Manager's settings can be opened using the **Settings** menu:
```suggestion
The Project Manager's settings can be opened using the **Settings** menu:
```

2024-06-28 12:03 UTC, AThousandShips commented on tutorials/editor/project_manager.rst
> +Favorited folders will be displayed on the left side under **Favorites** section. You can sort the
```suggestion
Favorited folders will be displayed on the left side under the **Favorites** section. You can sort the
```

2024-06-28 12:03 UTC, AThousandShips commented on tutorials/editor/project_manager.rst
> +Last chosen folders will be listed under **Recent** list.
```suggestion
Last chosen folders will be listed under the **Recent** list.
```

2024-06-28 12:03 UTC, AThousandShips commented on tutorials/editor/project_manager.rst
> +Last button on the right will create a new folder.
```suggestion
The last button on the right will create a new folder.
```

2024-06-28 12:03 UTC, AThousandShips commented on tutorials/editor/project_manager.rst
> +Next, the buttons to switch the display type of the folders and files between grid view to list view
```suggestion
Next, the buttons to switch the display type of the folders and files between grid view and list view
```
"between" doesn't indicate a one directional relationship, so "and" not "to"

2024-06-28 12:03 UTC, AThousandShips commented on tutorials/editor/project_manager.rst
> +Up arrow navigates to parent folder.
```suggestion
The up arrow navigates to parent folder.
```

2024-06-28 12:03 UTC, AThousandShips commented on tutorials/editor/project_manager.rst
> +Left of the path field on the top row contains arrows to navigate back and forward through last
```suggestion
Left of the path field on the top row contains arrows to navigate backward and forward through the last
```
Or
```suggestion
Left of the path field on the top row contains arrows to navigate backward and forward through recently
```

Either "back and forth" or "backward and forward"

2024-06-28 12:31 UTC, AThousandShips commented
Please apply changes in a batch using "add suggestion to batch" to avoid creating a lot of commits

2024-06-28 12:33 UTC, vgezer commented
> Please apply changes in a batch using "add suggestion to batch" to avoid creating a lot of commits

Yes, made the same mistake again :).

2024-06-28 12:35 UTC, vgezer commented
> I'd suggest perhaps splitting this into multiple PRs for each area of the documentation, as it touches on pretty different areas

I thought about it, but I had to move the text to other relevant documents, not to lose the information. E.g., some text from `first-look-at-interface` was moved to `project-settings`. At the end multiple files were modified.

2024-06-28 12:37 UTC, AThousandShips commented
Will give this a second review for content as well soon

2024-07-15 17:27 UTC, AThousandShips commented on tutorials/editor/project_manager.rst
> +using multiple tags, you can click on another tag or add ``tag:``tag: after
```suggestion
using multiple tags, you can click on another tag or add ``tag:`` after 
```

2024-07-15 17:27 UTC, AThousandShips commented on tutorials/editor/project_manager.rst
> +another machine and import it into the project manager you will see the tags
```suggestion
another machine, and import it into the project manager you will see the tags
```

2024-07-15 17:27 UTC, AThousandShips approved these changes
LGTM

2024-07-27 02:08 UTC, skyace65 approved these changes

2024-07-27 02:09 UTC, skyace65 requested changes
This PR needs to be rebased. There's a conflict with proejct_manager.rst

2024-07-28 19:35 UTC, skyace65 approved these changes

2024-07-28 19:38 UTC, merged

2024-07-28 19:38 UTC, skyace65 commented
Thanks!