Add 2D Parallax documentation page
godotengine/godot-docs pull request #9587
Opened 2024-07-09 20:11 UTC by markdibarry

This adds a page to clarify using `Parallax2D`, provides visual examples, and explains some common pitfalls.

2024-07-10 16:06 UTC, mhilbrunner reviewed
Great work, thank you! A few thoughts below, I gave it a read and found no issues otherwise.

2024-07-10 16:06 UTC, mhilbrunner commented on tutorials/2d/2d_parallax.rst
> +We can see that the viewport size is ``500 x 300`` but the texture is ``288 x 208``. If we set the
```suggestion
We can see that the viewport size is 500×300 but the texture is 288×208. If we set the
```
Either no formatting, or alternatively just for the numbers. I think this is fine? Also unsure whether we should add "pixel", but this is probably clear enough as is.

2024-07-10 16:06 UTC, mhilbrunner commented on tutorials/2d/2d_parallax.rst
> +used to offset where the infinite repeat canvas starts. As an example, if your image is ``288 x 208``, setting
```suggestion
used to offset where the infinite repeat canvas starts. As an example, if your image is 288×208, setting
```

2024-07-10 16:06 UTC, mhilbrunner commented on tutorials/2d/2d_parallax.rst
> +Until now, we have had a perfectly fitting ``288 x 208`` texture inside of a ``288 x 208`` viewport. However, problems
```suggestion
Until now, we have had a perfectly fitting 288×208 texture inside of a 288×208 viewport. However, problems 
```

2024-07-10 16:06 UTC, mhilbrunner commented on tutorials/2d/2d_parallax.rst
> +also something that even experienced users struggle to wrap their heads around. Godot provides the
```suggestion
Parallax is an effect used to simulate depth by having textures move at different speeds relative to the camera. Godot provides the
```
IMO that does not add much :)

2024-07-10 16:46 UTC, markdibarry commented
Thanks! I'm not as familiar with rst file syntax, so if you have any suggestions for formatting, feel free!

There's a lot of users I've talked to who get stuck on parallax after following tutorials that also misunderstand how the effect works. I've been compiling some FAQs regarding parallax from the community and wanted to at least get some thoughts down and a basis to build off of. This should at least serve as a reference for any new tutorials that come out after 4.3. There's a lot to improve on this, so if you see anything tone-related, grammar, or something to expand/condense, please let me know!

2024-07-13 18:15 UTC, skyace65 requested changes
Content is good, only one thing really needs to be changed. We need to be clear that the node is experimental, but that we still recommend using it over the old method.

2024-07-13 18:15 UTC, skyace65 commented on tutorials/2d/2d_parallax.rst
> +up though, so this page provides in-depth descriptions of some properties and how to fix some common mistakes.
```suggestion
provides the :ref:`Parallax2D<class_parallax2d>` node to achieve this effect. This node is still experimental, so the
implementation might change in future versions of Godot. However it is still recommended to use this over the old method, using the
:ref:`ParallaxLayer<class_parallaxlayer>` and :ref:`ParallaxBackground<class_parallaxbackground>` nodes. As such this page
will only cover how to use :ref:`Parallax2D<class_parallax2d>`.
```

2024-07-13 18:33 UTC, markdibarry commented
Great catch! I added a note.

2024-07-14 02:37 UTC, skyace65 approved these changes

2024-07-15 05:43 UTC, mhilbrunner approved these changes
Built this locally and had a quick look, spotted nothing else. Great work!

2024-07-15 05:44 UTC, merged