Update standard_material_3d.rst to Godot 4
godotengine/godot-docs pull request #9641
Opened 2024-07-23 17:35 UTC by cake-pie

*Depth* renamed to *Height*; heading updated in #4587 but missed a mention in paragraph text.

2024-07-23 19:02 UTC, clayjohn approved these changes
Looks good. Nice catch!

2024-07-23 22:22 UTC, skyace65 approved these changes

2024-07-23 22:25 UTC, skyace65 reviewed
@clayjohn at the beginning of that section, should "depth map" be changed to "height map"?

2024-07-24 03:23 UTC, cake-pie commented
> "depth map" be changed to "height map"?

You're right; I'll adjust that too.

Would it be helpful to also add a note + pointer to `HeightMapShape3D`? For any readers landing here while searching for use cases such as procedurally generated terrain heightmaps.

```diff
- This is not real added geometry, but an illusion of depth.
+ This only creates an illusion of depth, and does not add real geometry — for height map
+ shape used for physics collision (such as terrain) see :ref:`class_HeightMapShape3D`.
```

2024-07-24 21:15 UTC, clayjohn commented
> Would it be helpful to also add a note + pointer to `HeightMapShape3D`? For any readers landing here while searching for use cases such as procedurally generated terrain heightmaps.
> 
> ```diff
> - This is not real added geometry, but an illusion of depth.
> + This only creates an illusion of depth, and does not add real geometry — for height map
> + shape used for physics collision (such as terrain) see :ref:`class_HeightMapShape3D`.
> ```

I think so!

2024-07-26 03:34 UTC, cake-pie commented
Done!

2024-07-27 06:11 UTC, Calinou commented on tutorials/3d/standard_material_3d.rst
> +for physics collision (such as terrain) see :ref:`class_HeightMapShape3D`. It
```suggestion
for physics collision (such as terrain), see :ref:`class_HeightMapShape3D`. It
```

2024-07-27 06:11 UTC, Calinou approved these changes

2024-08-01 01:43 UTC, skyace65 requested changes
Just one minor change and this should be good.

2024-08-01 01:43 UTC, skyace65 commented on tutorials/3d/standard_material_3d.rst
> +illusion of depth, and does not add real geometry — for height map shape used
```suggestion
illusion of depth, and does not add real geometry — for a height map shape used
```

2024-08-01 22:01 UTC, skyace65 approved these changes

2024-08-01 22:11 UTC, merged

2024-08-01 22:12 UTC, skyace65 commented
Thanks! And congrats on your first merged PR! In the future please keep PRs to 1 commit, I did a squash and merge this time but keep it in mind for the future. If you don't know how to do that we have a guide [here](https://docs.godotengine.org/en/stable/contributing/workflow/pr_workflow.html#modifying-a-pull-request)

2024-08-02 02:42 UTC, cake-pie commented
Noted, thanks!