Update "Compiling for Windows" page.
godotengine/godot-docs pull request #9650
Opened 2024-07-24 19:54 UTC by bruvzg

- Adds notes related to ARM64 compilation (MinGW-LLVM links and commands).
- Updates ANGLE build instructions.
- Updates custom export templates image.

2024-07-25 02:19 UTC, skyace65 requested changes
The image should be a webp not a png. Also the lines should be the same yellow that's used on other pages of the documentation. The ones you made look a bit...shakey, not sure how else to describe it. If you send me the png without lines I can edit the image for you.

Also does this mean we have out of the box ARM support for Windows in 4.3?

2024-07-25 06:25 UTC, bruvzg commented
Switched to `webp` with solid lines.

> Also does this mean we have out of the box ARM support for Windows in 4.3?

Yes, for custom builds it was supported for a long time. And official build containers and scripts were recently updated to include it, so next release should have ARM64 Windows editor and templates.

2024-07-25 08:49 UTC, AThousandShips commented on contributing/development/compiling/compiling_for_windows.rst
> +  Supports ``x86_64``, ``x86_32`` and ``arm64``.
```suggestion
  Supports ``x86_64``, ``x86_32``, and ``arm64``.
```

2024-07-25 08:49 UTC, AThousandShips commented on contributing/development/compiling/compiling_for_windows.rst
> +  Supports ``x86_64``, ``x86_32`` and ``arm64``.
```suggestion
  Supports ``x86_64``, ``x86_32``, and ``arm64``.
```

2024-07-26 02:25 UTC, skyace65 requested changes
The color for the outlines still needs to be changed. It should be yellow like in this image: 
![ExampleColor](https://github.com/user-attachments/assets/c43cc8b8-b71e-4085-87af-ab7cbf90e09b)

hex code is fffb44 (fffb44ff if there's a transparency value)

2024-07-26 07:40 UTC, bruvzg commented
> The color for the outlines still needs to be changed. It should be yellow like in this image:

Done. Seems like it a bit of a mess right now, different parts of the docs use different style, probably should be cleaned up:
<img width="1424" alt="Screenshot 2024-07-26 at 10 39 00" src="https://github.com/user-attachments/assets/79aacfb2-c89b-4ca7-b40a-bd74956a4ad2">

2024-07-26 11:02 UTC, skyace65 approved these changes

2024-07-26 11:02 UTC, skyace65 commented
> > The color for the outlines still needs to be changed. It should be yellow like in this image:
> 
> Done. Seems like it a bit of a mess right now, different parts of the docs use different style, probably should be cleaned up: <img alt="Screenshot 2024-07-26 at 10 39 00" width="1424" src="https://private-user-images.githubusercontent.com/7645683/352439961-79aacfb2-c89b-4ca7-b40a-bd74956a4ad2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5OTIwMjQsIm5iZiI6MTcyMTk5MTcyNCwicGF0aCI6Ii83NjQ1NjgzLzM1MjQzOTk2MS03OWFhY2ZiMi1jODliLTRjYTctYjQwYS1iZDc0OTU2YTRhZDIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjZUMTEwMjA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDliMGE1NTRhNmI0ZTNhZTgxMTdmMTEzYTdhM2Y2MzUwYjdhMDMzY2I2ZmY0NDlkZTRhZTBkZjMzYjYzODEzNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.BacbwzwLNJMWo6kbO28Bl0kt3HIaL4zn6OFxb34nqkE">

Yeah, the current goal is to get everything standardized as images need to be updated.

2024-07-27 06:09 UTC, Calinou approved these changes
Looks great!

2024-07-27 22:07 UTC, mhilbrunner approved these changes

2024-07-27 22:07 UTC, merged

2024-07-27 22:07 UTC, mhilbrunner commented
Thank you! 🙏