Add C# examples to Using NavigationMaps
godotengine/godot-docs pull request #9812
Opened 2024-08-23 11:58 UTC by ShawnHardern

Add C# examples to Using NavigationMaps

2024-08-23 13:44 UTC, smix8 approved these changes

2024-08-23 16:30 UTC, raulsntos requested changes

2024-08-23 16:30 UTC, raulsntos commented on tutorials/navigation/navigation_using_navigationmaps.rst
> +    public partial class MyClass : Node2D
We usually follow the pattern `My{BaseClass}` for naming classes in the docs, unless the GDScript version names them explicitly with `class_name`.

```suggestion
    public partial class MyNode2D : Node2D
```

2024-08-23 16:30 UTC, raulsntos commented on tutorials/navigation/navigation_using_navigationmaps.rst
> +    public partial class MyClass : Node3D
```suggestion
    public partial class MyNode3D : Node3D
```

2024-08-23 16:30 UTC, raulsntos commented on tutorials/navigation/navigation_using_navigationmaps.rst
> +    public partial class MyClass : Node2D
```suggestion
    public partial class MyNode2D : Node2D
```

2024-08-23 16:30 UTC, raulsntos commented on tutorials/navigation/navigation_using_navigationmaps.rst
> +    public partial class MyClass : Node3D
```suggestion
    public partial class MyNode3D : Node3D
```

2024-08-23 16:30 UTC, raulsntos commented on tutorials/navigation/navigation_using_navigationmaps.rst
> +            Rid defaultNavigationMapRid = GetWorld2D().GetNavigationMap();
Prefer properties to hidden methods.

```suggestion
            Rid defaultNavigationMapRid = GetWorld2D().NavigationMap;
```

2024-08-23 16:30 UTC, raulsntos commented on tutorials/navigation/navigation_using_navigationmaps.rst
> +            Rid defaultNavigationMapRid = GetWorld3D().GetNavigationMap();
```suggestion
            Rid defaultNavigationMapRid = GetWorld3D().NavigationMap;
```

2024-08-23 16:47 UTC, raulsntos approved these changes

2024-08-23 16:48 UTC, merged

2024-08-23 16:48 UTC, AThousandShips commented
Thanks! And congratulations on your first merged contribution! 🎉

2024-10-04 02:22 UTC, mhilbrunner commented
Cherry-picked to 4.3 in https://github.com/godotengine/godot-docs/pull/10038.