Add a workflow to the docs explaining how to retain the value of renamed exported properties
godotengine/godot-docs pull request #9900
Opened 2024-09-04 14:39 UTC by AdriaandeJongh

All feedback is welcome!

2024-09-04 16:12 UTC, MaaaxiKing requested changes
typo

2024-09-04 16:12 UTC, MaaaxiKing commented on tutorials/scripting/gdscript/gdscript_exports.rst
> +   re-save them. The properties should have successfully transfered!
```suggestion
   re-save them. The properties should have successfully transferred!
```

2024-09-04 18:18 UTC, AdriaandeJongh commented on tutorials/scripting/gdscript/gdscript_exports.rst
> +2. Add the ``@tool`` annotation to the script with the exported property you want to rename.
Hmm, I hear you. These two scenarios are very suboptimal and potentially a lot of work, so they do make me circle back to my original proposal of adding a much more user-friendly `@exported_previously_as('<property_name>')` annotation to simply 'make it work' for users. In my 12 years of game dev making 10+ games, I've found that refactoring is an important and very often used tool in game development, and so anything to soften the blow would help. 

@dalexeev do you think I should expand this PR with your additional methods / workarounds / workflows, or do you think the challenges of refactoring are addressed with other features on the timeline and these additions to the docs will be out of date soon?

2024-09-19 08:37 UTC, closed without merging

2024-09-19 08:37 UTC, AdriaandeJongh commented
This isn't a good workaround / solution after all, as explained in @dalexeev's review. I'm hoping a better workflow can be proposed and implemented.