Update physics_introduction.rst
godotengine/godot-docs pull request #9910
Opened 2024-09-05 02:23 UTC by D4Devil

Added examples for independently setting bits on mask and layer

2024-09-05 09:56 UTC, AThousandShips commented on tutorials/physics/physics_introduction.rst
> +can use binary, hexadecimal, or decimal notation for layer masks depending
Please restore, unrelated and an appropriate pause

2024-09-05 09:57 UTC, AThousandShips commented on tutorials/physics/physics_introduction.rst
> +You can also set bits independently by calling 'set_collision_layer_value(layer_number, value)'
```suggestion
You can also set bits independently by calling ``set_collision_layer_value(layer_number, value)``
```

2024-09-05 09:57 UTC, AThousandShips commented on tutorials/physics/physics_introduction.rst
> +or 'set_collision_mask_value(layer_number, value)' on any given :ref:`CollisionObject <class_CollisionObject2D>` as follows::
```suggestion
or ``set_collision_mask_value(layer_number, value)`` on any given :ref:`CollisionObject <class_CollisionObject2D>` as follows::
```

2024-09-05 09:57 UTC, AThousandShips commented on tutorials/physics/physics_introduction.rst
> +    # Example: Setting mask value for enabling layers 1, 3 and 4
```suggestion
    # Example: Setting mask value for enabling layers 1, 3, and 4.
```

2024-09-05 20:02 UTC, D4Devil commented
@AThousandShips Thanks for the corrections

2024-11-07 01:19 UTC, tetrapod00 requested changes
I tested the code (with the function name correction applied). It does work to set the bits of the collision mask one at a time.

2024-11-07 01:19 UTC, tetrapod00 commented on tutorials/physics/physics_introduction.rst
> +or ``set_collision_mask_value(layer_number, value)`` on any given :ref:`CollisionObject <class_CollisionObject2D>` as follows::
```suggestion
or ``set_collision_mask_value(layer_number, value)`` on any given :ref:`CollisionObject2D <class_CollisionObject2D>` as follows::
```
Use the whole name

2024-11-07 01:19 UTC, tetrapod00 commented on tutorials/physics/physics_introduction.rst
> +    collider.set_mask_layer_value(4, true)
```suggestion
    collider.set_collision_mask_value(1, true)
    collider.set_collision_mask_value(3, true)
    collider.set_collision_mask_value(4, true)
```
The function name was wrong in the example, there is no `set_mask_layer_value()` function

2024-11-19 22:46 UTC, tetrapod00 approved these changes

2024-11-20 00:12 UTC, merged