Fix typos in FAQ and CompositorEffect class reference
godotengine/godot-docs pull request #9978
Opened 2024-09-19 19:58 UTC by jirisvd

This PR:
- Changes `build in post effects` to `built-in post-processing effects` in `CompositorEffect` class reference
- Adds missing word in FAQ answer (`once you see how powerful it is and [how] rapid your development becomes`)

2024-09-19 20:02 UTC, AThousandShips requested changes

2024-09-19 20:02 UTC, AThousandShips commented on classes/class_compositoreffect.rst
These changes needs to be done over [here](https://github.com/godotengine/godot), changing the generated files is not allowed, see [here](https://docs.godotengine.org/en/latest/contributing/documentation/updating_the_class_reference.html)

2024-09-19 20:15 UTC, jirisvd commented on classes/class_compositoreffect.rst
My bad, I force pushed a new commit so that only the FAQ fix remains, should be good now

2024-09-20 00:37 UTC, mhilbrunner approved these changes

2024-09-20 01:44 UTC, merged

2024-09-20 01:44 UTC, mhilbrunner commented
Merged. Thanks and congrats on your first merged contribution!

2024-10-04 02:13 UTC, mhilbrunner commented
Cherry-picked to 4.3 in https://github.com/godotengine/godot-docs/pull/10038.